### PR TITLE
General fixes and readability changes

### PR DESCRIPTION
**Pull request by oliverfoster**
* fix to buttonsview to remove marking classes properly
* isoptional fix to adaptmodel
* readability changes to adaptmodel and questionview

### CODE REVIEW

**Comment by brian-learningpool** [comment]
I'm happy enough to approve this but for consistency shouldn't there be a space after the `if` statements?

**Comment by oliverfoster** [comment]
i need to slow down it seems.

**Comment by brian-learningpool** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by moloko** [comment]
+1

**Pull request merged**
