### PR TITLE
issue-1438: added backbone.controller

### PR DESCRIPTION
**Pull request by oliverfoster**
Make code clearer by having a Backbone class for Controllers:

fixes issue: https://github.com/adaptlearning/adapt_framework/issues/1438

added backbone.controller from https://github.com/cgkineo/backbone.controller

### CODE REVIEW

**Comment by moloko** [comment]
Tested in Firefox with accessibility on, also quick SCORM test via the test harness and quick check of start controller by setting start page to co-05

**Comment by moloko** [comment]
did a very quick check in IE11 too

**Comment by oliverfoster** [comment]
Ta :) much appreciated.

**Comment by oliverfoster** [comment]
@moloko would you mind re-reviewing? was just the ``BUTTON_STATE.SHOW_CORRECT_ANSWER`` to ``_buttons['_showCorrectAnswer'].text`` and ``_buttons['_showCorrectAnswer'].ariaLabel`` conversion

**Comment by oliverfoster** [comment]
@moloko would you mind re-reviewing, was just merge fixes for the ``BUTTON_STATE`` conflict on logging

**Pull request merged**
