### PR TITLE
issue-1233: added grunt diff

### PR DESCRIPTION
**Pull request by oliverfoster**
This task is a dev rebuild, checking if files are newer and recompiling if necessary.
It doesn't do a watch or a clean.

Only performs a check on LESS, Handlebars and JavaScript

### CODE REVIEW

**Comment by aniketdharia** [comment]
:+1:

**Comment by aniketdharia** [comment]
Olli but I think for dev we should keep watch else the developer will need to run command everytime he updates a JSON.. what are your thoughts?

**Comment by taylortom** [comment]
@aniketdharia this PR has no effect on the dev task?

**Comment by aniketdharia** [comment]
Oops .

Got it..

**Comment by lc-thomasberger** [comment]
Nice one! Would be good to have a Version of this that watches for json and js/less. If it listens to json changes, you get a really fast compilation time when adding content to the course.

**Comment by oliverfoster** [comment]
+1 @thomas yea, should be pretty easy - following the same pattern.

**Comment by aniketdharia** [comment]
+1

**Comment by aniketdharia** [comment]
Should we merge?

**Comment by oliverfoster** [comment]
@lc-thomasberger  it takes almost as much time to check if the json is newer as it does to rebuild it and the extra config needed it quite big. can we leave the json out for the moment?

**Comment by sarveshwar-gavhane** [comment]
@oliverfoster  it would be the good enhancement for newer file checking and last modified source files, when will this changes are pushed into the framework.

**Comment by oliverfoster** [comment]
@sarveshwar-gavhane i need to get the 3 +1s on it

**Comment by sarveshwar-gavhane** [comment]
@oliverfoster can we close  https://github.com/adaptlearning/adapt_framework/issues/1445 with this PR or a separate one ?

**Comment by oliverfoster** [comment]
a separate one would be good (y)

**Pull request merged**
