### PR TITLE
issue/3121 Added fw and plugin version detection

### LINKED ISSUE #3121: adapt_framework: plugin and framework version comparisons
### Subject of the issue
It's currently difficult at runtime to ascertain the version of the framework and installed plugins.

Suggested additions, using [semver](https://semver.org/):
```js
Adapt.build.isFrameworkVersion('=5.12.2');
Adapt.build.isFrameworkVersion('>4 <6');
Adapt.build.isPluginInstalled('adapt-contrib-trickle', '^5');
Adapt.build.isPluginInstalled('adapt-contrib-trickle');
```

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #3121 

### Added
* `Adapt.build.isFrameworkVersion(version);`
* `Adapt.build.isPluginInstalled(name, version);`

### CODE REVIEW

**Review by moloko — APPROVED** [review]
code 👓

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by tomgreenfield — COMMENTED** [review]
Could we `{ includePrerelease: true }` in these functions please?

**Review by moloko — APPROVED** [review]

**Review by tomgreenfield — APPROVED** [review]
:eye:

**Pull request merged**
