### PR TITLE
Revert grunt-contrib-handlebars to ~0.5.11

### PR DESCRIPTION
**Pull request by taylortom**
Can't run course with the current handlebars version

### CODE REVIEW

**Comment by oliverfoster** [comment]
Tested and working with the fix.

**Comment by moloko** [comment]
+1

**Comment by hrajotia** [comment]
@taylortom according to this http://github.com/gruntjs/grunt-contrib-handlebars#release-history, they have updated Handlebars to version 2.0. So I thinks this what making trouble here so if we change version of `grunt-contrib-handlebars` to `~0.8.0` then it should work.

what you think?

**Comment by oliverfoster** [comment]
We would have to check if the client and grunt versions are compatible. Have you tested .8.0 with the grunt task to see if the test course works? @hrjotia

**Comment by oliverfoster** [comment]
To be honest I'd like to see us upgrade to version 2 in core libraries and grunt but include the full library rather than just the runtime.

**Comment by hrajotia** [comment]
@oliverfoster - yeah `"grunt-contrib-handlebars": "~0.8.0"`is working for me.

**Comment by oliverfoster** [comment]
also confirmed working with ~0.8.0, looks like we're good

**Comment by taylortom** [comment]
Done.

I'm assuming that this will be revisited with this ticket: https://adaptlearning.atlassian.net/browse/ABU-383?filter=10202, so as long as the build works now, I don't think it will matter much which version we're on.

**Pull request merged**
