### PR TITLE
Add RTL support

### PR DESCRIPTION
**Pull request by taylortom**
Outstanding branch from the RTL work. Looks good from my tests.

### CODE REVIEW

**Comment by dancgray** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by brian-learningpool** [comment]
Is the indentation a bit funky in some of these?

**Comment by taylortom** [comment]
Yeah, will have a look at that in a bit

**Comment by taylortom** [comment]
Should be all good now

**Comment by oliverfoster** [comment]
+1

**Comment by dancgray** [comment]
+1

**Comment by moloko** [comment]
+1

**Pull request merged**
