### PR TITLE
Fix #1670: RTL vertical align of components

### LINKED ISSUE #1670: RTL vertical align of components is wrong
When placing two components in a block and the course uses RTL as _defaultDirection, then the vertical alignment is done wrong. The component on the right on large screens should be aligned on top on small screens. Right now it is the opposite:

The following screenshot already shows the right behaviour:

rtl-issue-vertical

### PR DESCRIPTION
**Pull request by dasistwas**
Fixes vertical alignment issue for RTL course configuration described in https://github.com/adaptlearning/adapt_framework/issues/1670

### CODE REVIEW

**Comment by brian-learningpool** [comment]
@lc-thomasberger, is there an impact on multi-language courses here?

**Comment by oliverfoster** [comment]
is there a course.json specific rtl value? or it is only done in the config.json?

**Comment by moloko** [comment]
@oliverfoster `_defaultDirection` initially gets set via config.json but then can be changed by plugins like [languagePicker](https://github.com/adaptlearning/adapt-contrib-languagePicker)

**Comment by brian-learningpool** [comment]
Perfect, we're covered with this PR then. 👍

**Comment by oliverfoster** [comment]
ta @moloko

**Pull request merged**
