### PR TITLE
Library updates

### PR DESCRIPTION
**Pull request by oliverfoster**
tested with ie8 and chrome, is much faster.

backbone not updated as options behaviour has changed in instanciation of models and views.

made templates into 'require' module to ensure load sequence and bring handlebars inline with latest version.

### CODE REVIEW

**Comment by oliverfoster** [comment]
#507

**Comment by brian-learningpool** [comment]
+1

**Comment by dancgray** [comment]
+1

**Comment by taylortom** [comment]
+1

**Pull request merged**
