### PR TITLE
issue/910: added requireCompletionOf: X

### PR DESCRIPTION
**Pull request by oliverfoster**
#910 

if you need all of the mandatory components to be complete use _requireCompletionOf: -1  (this is as default)
if you need to exclude some of the mandatory components from completion use _isOptional: true (making them non-mandatory)
if you need only X number of mandatory components to complete, use requireCompletionOf: X

### CODE REVIEW

**Comment by LukaszGrela** [comment]
+1

**Comment by moloko** [comment]
+1
This does all need documenting somewhere of course

One thing to note is that setting `_requireCompletionOf` to `0` triggers much the  the same behaviour as setting `_isOptional` on all components in the block - except that the PLP will not show those components as being optional. I don't think this is problem, so long as we're clear that it does this - perhaps we should recommend in the docs that `_isOptional` is the better method for making all components in a block optional?

**Comment by oliverfoster** [comment]
might be better to make if "0" : false / off ? that way we remove the ambiguity? or introduce more?

**Comment by taylortom** [comment]
+1
Don't think it particularly matters if it's the default? Otherwise, I'd maybe prefer a value like "all" to a number.

**Pull request merged**
