### PR TITLE
Lukasz grela patch issue #804

### PR DESCRIPTION
**Pull request by LukaszGrela**
check on the existence of _classes property so there are not `undefined` in the class list, fix issue #804

### CODE REVIEW

**Comment by moloko** [comment]
+1

**Comment by oliverfoster** [comment]
+1

**Comment by brian-learningpool** [comment]
-1, sorry @LukaszGrela, I actually think that @oliverfoster's suggestion of moving the default to the AdaptModel.js is a more elegant solution.  As all these views inherit from AdaptView you also could've added the default there.

**Comment by LukaszGrela** [comment]
@brian-learningpool I do agree that one place is best:) however (I have to check again) my attempt was unsuccessful with using model and also this will add `_classes` to all models that not necessarily are using it.

**Comment by brian-learningpool** [comment]
On reflection, PageView, ArticleView, BlockView and ComponentView all inherit from AdaptView so I think this is probably a better place to put it.

**Comment by LukaszGrela** [comment]
@brian-learningpool like so?

```
        initialize: function() {
            this.listenTo(Adapt, 'remove', this.remove);
            this.listenTo(this.model, 'change:_isVisible', this.toggleVisibility);
            this.model.set('_globals', Adapt.course.get('_globals'));
            this.model.set('_isReady', false);

            if (!this.model.has('_classes')) this.model.set('_classes', '');

            this._isRemoved = false;
            this.preRender();
            this.render();
        },
```

**Comment by brian-learningpool** [comment]
Hi @LukaszGrela, yes that's what I was thinking.  Does that resolve it for you?

**Comment by oliverfoster** [comment]
className() executes as the containing DOM object is created, which is done before initialize() is called. The DOM object will already contain class="undefined" by that point. You'll have to do it as a default on the model if this is to be a global fix.

**Comment by LukaszGrela** [comment]
Adding `_classes` to the defaults of the `AdaptModel` works
```
defaults: {
            _canShowFeedback: true,
            _canReset: false,
            _isComplete: false,
            _isInteractionComplete: false,
            _isEnabled: true,
            _isResetOnRevisit: false,
            _isAvailable: true,
            _isOptional: false,
            _isTrackable: true,
            _isReady: false,
            _isVisible: true,
            _classes: ''
        }
```

however I feel it is wrong as this adds property that may not be used by all children of this model, could we just extend `defaults` in the proper models like so:

```
    var BlockModel = AdaptModel.extend({
        _parent: 'articles',
        _siblings: 'blocks',
        _children: 'components',
        defaults: _.extend({}, AdaptModel.prototype.defaults, {
            _classes: ''
        })
    });
```

**Comment by oliverfoster** [comment]
The simple one works best and fits in with the way everything else works. If you add it to defaults now we can have a discussion about view and model separation when we do the next major version?

**Comment by taylortom** [comment]
@LukaszGrela @oliverfoster what's the status on this? are we still aiming to get it in?

**Comment by oliverfoster** [comment]
closed for alternate pr #1012

**Pull request closed without merging**
