### PR TITLE
issue/1572: fixed compile helper context

### PR DESCRIPTION
**Pull request by oliverfoster**
#1572

### CODE REVIEW

**Comment by samumist** [comment]
This does fix the problem we saw on the menu page. `Hello {{_globals._learnerInfo.firstname}} ` in the `body` of `course.json` shows correctly on the menu page as `Hello Student`. 

However, the same `Hello {{_globals._learnerInfo.firstname}} ` in a text component shows just `Hello {{_globals._learnerInfo.firstname}}`  on the page.

**Comment by oliverfoster** [comment]
i'm not sure without testing it
https://github.com/adaptlearning/adapt-contrib-text/blob/master/templates/text.hbs#L2
https://github.com/adaptlearning/adapt_framework/blob/master/src/core/templates/partials/component.hbs#L9

both look fine. old theme maybe?

**Comment by samumist** [comment]
nop. 
I'm testing this with a new sample course build with release 2.1.0.

**Comment by oliverfoster** [comment]
it's because the vanilla theme changes haven't been released yet https://github.com/adaptlearning/adapt-contrib-vanilla/releases/tag/v2.0.4 < there are 22 outstanding commits
try deleting the templates folder from your theme or copying the partials/component.hbs from core/templates/partials/component.hbs

**Comment by samumist** [comment]
Yes. 
All looks good after vanilla theme components template update.

+1

**Comment by oliverfoster** [comment]
ta @samumist

**Pull request merged**
