### PR TITLE
issue-1874 - updating destination of menuAssets

### PR DESCRIPTION
**Pull request by ciaranlp**
Updating destination for menuAssets
#1874

### CODE REVIEW

**Comment by oliverfoster** [comment]
this will break any menu which uses the assets folder as it is at the moment

**Comment by oliverfoster** [comment]
please see proposal at https://github.com/adaptlearning/adapt_framework/issues/1874#issuecomment-346094441

**Comment by lc-thomasberger** [comment]
Should this go into v3 of the Framework?

**Comment by oliverfoster** [comment]
I think it can go into any version @lc-thomasberger assuming we can smooth the breaking issues.

**Comment by oliverfoster** [comment]
@ciaranlp if you're happy with the other [pr](https://github.com/adaptlearning/adapt_framework/pull/1932) can I close this one?

**Pull request closed without merging**
