### PR TITLE
Version 2 Upgrade

### PR DESCRIPTION
**Pull request by zenduo**

### CODE REVIEW

**Comment by moloko** [comment]
+1

**Comment by zenduo** [comment]
Just added a few content fixes to the course text.

Fixes these:
https://adaptlearning.atlassian.net/browse/ABU-526
https://adaptlearning.atlassian.net/browse/ABU-529
https://adaptlearning.atlassian.net/browse/ABU-532
https://adaptlearning.atlassian.net/browse/ABU-540
https://adaptlearning.atlassian.net/browse/ABU-541
https://adaptlearning.atlassian.net/browse/ABU-548
https://adaptlearning.atlassian.net/browse/ABU-551

**Comment by oliverfoster** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by dancgray** [comment]
+1

**Pull request merged**
