### PR TITLE
Move PLP globals to correct place

### PR DESCRIPTION
**Pull request by dancgray**
Global aria labels for PLP have been moved to _globals. _extensions. _pageLevelProgress. Fixes missing end of PLP aria labels.

### CODE REVIEW

**Comment by oliverfoster** [comment]
+1

**Comment by oliverfoster** [comment]
need a hotfix for master?

**Comment by dancgray** [comment]
@oliverfoster, yes need to create hotfix PR for master as well. Looks like there are some menu globals in the wrong place and some redundant fields in _accessibility._ariaLabels. I might as well apply these changes in this PR as well.

**Comment by moloko** [comment]
+1

**Comment by oliverfoster** [comment]
Cool. And "visited": "Visited" on this one would be good as well, if you could?

**Comment by oliverfoster** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by moloko** [comment]
+1

**Pull request merged**
