### PR TITLE
Add accessibility icon

### PR DESCRIPTION
**Pull request by tomgreenfield**
Part of https://github.com/adaptlearning/adapt_framework/issues/1182.

Icon added from [IcoMoon - Free](https://icomoon.io/#preview-free) set.

### CODE REVIEW

**Comment by oliverfoster** [comment]
+1

**Comment by moloko** [comment]
can we see which one you added? can't tell from the changed files!

**Comment by tomgreenfield** [comment]
From the above link, type `accessibility` into the search. It's the little man.

**Comment by hrajotia** [comment]
+1

**Comment by guywillis** [comment]
+1

**Pull request merged**
