### PR TITLE
Fixes ABU-1128

### PR DESCRIPTION
**Pull request by taylortom**
Refactoring of the grunt process.
***
#### TODO:
- Fix up the `help` task

### CODE REVIEW

**Comment by taylortom** [comment]
@brian-learningpool brought up a fairly serious issue regarding **including** plugins (this is the method that we're going to be using in the AT):

If you include a plugin which inherits for something else, but not the original plugin (i.e. in the case of MCQ and GMCQ), you run into a sticky situation.

We need to solve this before this refactor can go in really.

**Comment by brian-learningpool** [comment]
For reference, this has been raised as #805.  In order to progress things though, a temporary/patch solution would be to support the core plugins which have dependencies on others.  Off the top of my head, the logic would be something like:
- ensure adapt-contrib-mcq is bundled if adapt-contrib-gmcq is bundled
- ensure adapt-contrib-narrative is bundled if adapt-contrib-hotgraphic is bundled
- ensure adapt-contrib-slider is bundled if adapt-contrib-confidenceSlider is bundled, 
etc.

Or we could add support for always bundling specific plugins (configurable) as part of the compilation?

**Comment by oliverfoster** [comment]
can we not list dependencies in the bower jsons and have it check when it bundles the plugins?

**Comment by taylortom** [comment]
That sounds sensible to me.

I think we also need to do something from the CLI end to pull in the relevant dependencies during an `adapt install`

**Comment by taylortom** [comment]
@oliverfoster @brian-learningpool see https://github.com/adaptlearning/adapt_framework/pull/818 for a partial fix for the dependencies. 

I think we also still need something from the CLI-side.

**Pull request closed without merging**
