### PR TITLE
issue-1156-1157: added handlebars to core

### PR DESCRIPTION
**Pull request by oliverfoster**
part of https://github.com/adaptlearning/adapt_framework/issues/954

this is one of the least contentious parts of moving some of the theme foundations into core

https://github.com/adaptlearning/adapt_framework/issues/1156

### CODE REVIEW

**Comment by tomgreenfield** [comment]
Time to remove the redundant maintainers comments?

**Comment by oliverfoster** [comment]
done

**Comment by tomgreenfield** [comment]
+1

**Comment by lc-thomasberger** [comment]
+1

**Comment by guywillis** [comment]
+1

**Comment by andrewhosgood** [comment]
Will there now be another way to change the markup for a specific theme without modifying the core or is this no longer possible?

**Comment by oliverfoster** [comment]
you can override any handlebars from the theme in the same way we do at the moment @andrewhosgood

**Pull request merged**
