### PR TITLE
issue-1303: updated to jquery 3.1.1

### PR DESCRIPTION
**Pull request by oliverfoster**
https://github.com/adaptlearning/adapt_framework/issues/1303

### CODE REVIEW

**Comment by brian-learningpool** [comment]
JQuery 3+ doesn't seem to support IE 8.
https://jquery.com/upgrade-guide/3.0/#browser-support

**Comment by moloko** [comment]
@brian-learningpool different jquery library is loaded for IE8

**Comment by brian-learningpool** [comment]
Great, thanks for clarifying.

**Comment by oliverfoster** [comment]
i thoroughly recommend you test this with all your commonly used plugins and extensions. it may break some of the more outlandish ones.

**Comment by brian-learningpool** [comment]
I guess we need a full regression test on a course with the core plugins before this is merged?

**Comment by oliverfoster** [comment]
I'm not so much worried about the core plugins. It's more 3rd party plugins I'm concerned will break. We need a way to mitigate that. I'm a bit lost in the jQuery migration docs. Perhaps you could have a read and suggest a decent course of action?

**Comment by brian-learningpool** [comment]
I will read when I get a chance.  Is there a pressing reason to upgrade to JQuery v3 at this moment or could it wait until the next major release of the framework?

**Comment by oliverfoster** [comment]
It can wait until we're all happy.

**Comment by moloko** [comment]
@brian-learningpool it's really just to take advantage of v3 (supposedly) being faster than v2

**Comment by moloko** [comment]
I just used JQuery v3 (and the updated inview) in a build where I was testing some updates made to confidenceSlider. Didn't notice any problems but it wasn't the most exhaustive of tests by any means. Only checked in Firefox for a start.

**Comment by moloko** [comment]
should we stick a post on the forums asking people to test this (and maybe inview as well)?

**Comment by brian-learningpool** [comment]
Hi @moloko, to answer your question (apologies for the delay), I think yes, we we should ask forum users to test this.

**Comment by moloko** [comment]
done: https://community.adaptlearning.org/mod/forum/discuss.php?d=1845

**Comment by moloko** [comment]
no feedback from forum users; agreed with @brian-learningpool to put this on hold until 02/02/17

**Pull request merged**
