### PR TITLE
Set correct version

### PR DESCRIPTION
**Pull request by taylortom**

### CODE REVIEW

**Comment by taylortom** [comment]
This'll also need to be done for develop

**Comment by brian-learningpool** [comment]
+1

**Comment by oliverfoster** [comment]
+1

**Comment by darylhedley** [comment]
Sorry - this is the wrong number
should be same as release: Adapt framework v1.1.1 as seen here
https://github.com/adaptlearning/adapt_framework/releases

**Comment by hrajotia** [comment]
+1

**Pull request merged**
