### PR TITLE
Javascript compilation: add support for filter

### LINKED ISSUE #975: Javascript compilation
Add support for a file filter. As it stands, we're still including empty define statements. Inspect the code in-browser (with source-mapping turned on) to see this.

### PR DESCRIPTION
**Pull request by taylortom**
Fixes #975

### CODE REVIEW

**Comment by brian-learningpool** [comment]
+1, I've tested this locally and it resolves the issue.  Nice work. :+1:

**Comment by oliverfoster** [comment]
+1

**Comment by bell87** [comment]
+1

**Comment by ryangadams** [comment]
+1

**Pull request merged**
