### PR TITLE
issue/949: notify:opened and notify:closed triggers

### PR DESCRIPTION
**Pull request by oliverfoster**
#949 

Allows extensions like trickle to monitor notify popups correct.

### CODE REVIEW

**Comment by tomgreenfield** [comment]
Probably best to remove [this line](https://github.com/adaptlearning/adapt_framework/blob/issue/949/src/core/js/views/notifyView.js#L50) too.

**Comment by oliverfoster** [comment]
ta

**Comment by tomgreenfield** [comment]
+1

**Comment by brian-learningpool** [comment]
+1

**Comment by moloko** [comment]
+1

**Pull request merged**
