### PR TITLE
Upgrade packages

### LINKED ISSUE #2187: NPM packages outdated
Getting some vunerability messages upon running `adapt create course`:
```shellsession
[!] 17 vulnerabilities found [1391 packages audited]
    Severity: 11 Low | 4 Moderate | 1 High | 1 Critical
    Run `npm audit` for more detail
```
It's high time we did a little upgrade.

### PR DESCRIPTION
**Pull request by tomgreenfield**
Resolves #2187.

Tested with Node 8 on Windows.

### CODE REVIEW

**Comment by moloko** [comment]
Like many others, I can't get the current version of adapt-cli to install on Win10 with Node v8 - so am unable to test if this still happens with the current version.

It does definitely only occur if I set up a course using this version of package.json - I have tried a couple of times using both this version and the version currently in master, the latter doesn't have this issue.

**Comment by tomgreenfield** [comment]
Seems like something got borked between `less@3.8.0` and `less@3.8.1`.

@oliverfoster, would you mind having a gander at the Less task when you're back?

**Comment by moloko** [comment]
were are we at with this @tomgreenfield ?

**Comment by tomgreenfield** [comment]
We should probably aim to get this in, if just to alleviate the one 'critical' vunerability.

**Pull request merged**
