### PR TITLE
add _ariaLevels to schema

### LINKED ISSUE #1941: Add _ariaLevel to schema
### Subject of the issue/enhancement/features
After [this pr](https://github.com/adaptlearning/adapt_framework/pull/1838) make sure schema is updated to include ``_ariaLevel`` attribute. Default to 0.

### PR DESCRIPTION
**Pull request by moloko**
fixes #1941 

also remove invalid uses of `isSetting`

### CODE REVIEW

**Comment by moloko** [comment]
hold off on reviewing until we've made a decision as to whether the child properties of `_ariaLevel` should be prefixed with an underscore or not

**Comment by oliverfoster** [comment]
There are two properties here. ```_ariaLevels``` as you have it are the default levels on the ```config.json``` and ```_ariaLevel```, which should pair with each title attribute. It should perhaps be called, ```_titleArialevel```.

```_ariaLevel```: is used [here](https://github.com/adaptlearning/adapt_framework/pull/1838/files#diff-767c220811484c7ab090ae86d2400d7dR148)
```_ariaLevels```: is used [here](https://github.com/adaptlearning/adapt_framework/pull/1838/files#diff-767c220811484c7ab090ae86d2400d7dR158)

```_ariaLevel``` on the component, block, article and contentObject should default to ``0`` so that it is considered "unset" and not override the default ```_ariaLevels``` value.

**Comment by moloko** [comment]
@oliverfoster added that in, could you check? 

also documented [here](https://github.com/adaptlearning/adapt_framework/wiki/Core-model-attributes#contentobjects-model-attributes)

**Comment by oliverfoster** [comment]
beautiful

**Comment by lc-thomasberger** [comment]
Since it is a limited number range, a dropdown might be easier to use.

**Comment by moloko** [comment]
> Since it is a limited number range, a dropdown might be easier to use.
In theory, it's unlimited. In practice, it seems unlikely that anyone's going to go much higher than, say, 10 I guess?

I'm happy to change it if people would prefer a drop down and are happy with a limit being placed on it

**Comment by oliverfoster** [comment]
10 seems waaay over reasonable. I'd be happy with 1-10

**Comment by moloko** [comment]
Can anyone point me in the direction of a .schema that uses a "Select" `inputType` to populate a `"number"` type field?

The only ones I can find are all for `"string"`...

**Comment by oliverfoster** [comment]
@tomgreenfield is there a select dropdown + number?

**Comment by tomgreenfield** [comment]
Haven't seen one but would most likely work, @oliverfoster.

My preference would be to keep as a [Number](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number) field for simplicity.

**Comment by lc-thomasberger** [comment]
Number field is fine for me.

**Comment by oliverfoster** [comment]
Can we get some +1's ? I know there is implied approval.

**Pull request merged**
