### PR TITLE
Implemented _isOptional behaviour

### PR DESCRIPTION
**Pull request by oliverfoster**
PLP needs updating to display optional states.

We need some discussion around this.

https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/42

### CODE REVIEW

**Comment by moloko** [comment]
+1

**Comment by zenduo** [comment]
+1

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/42 < jamie, any ideas for how plp should represent optional elements?

**Comment by danielghost** [comment]
I would maybe get a designers view on this but I would suggest an optional component appears as normal, displaying its own progress, but is excluded from the overall progress for the extension. In cases where an optional component should be excluded from the view completely this could be done by disabling it in the JSON.

**Comment by moloko** [comment]
I think generally one would not include optional components in the PLP

However, I'm sure there will be occasions when it is necessary to include them so perhaps we implement some method of styling them differently. I guess it would therefore make sense to add an 'optional' class to such items in the PLP to allow for that?

**Comment by dancgray** [comment]
+1

**Pull request merged**
