### PR TITLE
Grunt update

### PR DESCRIPTION
**Pull request by taylortom**
General tidying up of Gruntfile.js. Changes include:
- Fixed `watch` task
- Made sure src files are referenced consistently (fixes https://github.com/adaptlearning/adapt_framework/issues/544)
- Added getters for the dynamic variables for simplicity
- Removed `build/` after every reference to `<%= outputdir %>`, and instead moved this to getOutputDir (suggest altering slightly this so that the authoring tool supplies the `/build` prefix, and is not forcibly added to the end of the path)
- Src path is now dynamic to match theme
- Replaced all double quotes with single quotes for consistency
- Moved all package deps to devDeps
- Added some logs to various tasks (`build`, `dev`, `server`, `server-scorm`)

### CODE REVIEW

**Comment by oliverfoster** [comment]
+1 works fine, have been using it since posted, tested build, dev and server

**Comment by moloko** [comment]
+1

**Comment by oliverfoster** [comment]
i think leaving tracking-insert as the build/dev task is the least damaging. (as far as i understand it)  courses can be patched after they have been distributed, so the ids have to remain consistent

**Comment by oliverfoster** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Pull request merged**
