### PR TITLE
Issue 1030

### PR DESCRIPTION
**Pull request by bell87**
Added a check for `_isAvailable` on each model within the `findDescendants()` function which fixes progress indicators / completion of course.

This will mean that if an article isn't "available" then the descendants of the article won't be available either.

### CODE REVIEW

**Comment by barry-learningpool** [comment]
+1

**Comment by taylortom** [comment]
+1

**Comment by oliverfoster** [comment]
non of the other core model api traversal functions execute this way

**Comment by brian-learningpool** [comment]
@bell87, if this resolves the issue I think this would be cleaner if the code you've changed was moved directly to the Page Level Progress extension.

**Comment by oliverfoster** [comment]
seconded, filterAvailableChildren doesn't act upon the model. it's more like an extra utility function. well implemented though. 

a few notes:
array.map and array.indexOf aren't ie8 compatible, so you'll need to use the underscore versions. 
_.each is really inefficient, could you swap it for a for loop?

**Pull request closed without merging**
