### PR TITLE
issue/1802: inlined fix for duplicate handlebars templates

### PR DESCRIPTION
**Pull request by oliverfoster**
#1802
pulled in fix from https://github.com/gruntjs/grunt-contrib-handlebars/pull/147 as grunt-contrib-handlebars hasn't been updated in over a year

### CODE REVIEW

**Comment by oliverfoster** [comment]
@andrewhosgood

**Comment by andrewhosgood** [comment]
Yeah, I never heard anything more from the author on this one. Figured no one else thought it was important! :P

**Comment by oliverfoster** [comment]
Are you happy for me to include this in adapt? @andrewhosgood if so, can you check i've not adulterated your code and it works as expected, then give a +1 / accept ?

**Comment by andrewhosgood** [comment]
Of course, feel free!

**Pull request merged**
