### PR TITLE
issue/1998 remove buggy ios fixes for legacy branch

### LINKED ISSUE #1998: Remove ios specific a11y fixes
### Subject of the issue
Buggy code needs removing from a11y library.

### PR DESCRIPTION
**Pull request by jamesrea83**
Resolves #1998

### CODE REVIEW

**Comment by oliverfoster** [comment]
this is changing a lot more than just the buggy ios fixes.

**Comment by brian-learningpool** [comment]
A V2 patch?

**Comment by moloko** [comment]
@brian-learningpool yes it is

**Comment by moloko** [comment]
ignore my review, needs 1 non-Kineo person to review before it can be merged!

**Pull request merged**
