### PR TITLE
Accessibility integration 2

### PR DESCRIPTION
**Pull request by oliverfoster**
Traps tab on accessibility button if accessibility isn't on
Adds accessibility instructions for screen readers
Fixes popupmanager and tabindexes on popup/popdown
Wraps tab around to top of page from the bottom
Integrates jquery.a11y into the handlebars templates so that text blocks can become tabbable
Adds accessibility state rendering to componentView (is currently missing the 'state' partial as it needs to be added to theme)
Allows aria-labels to be read across all devices
Expands LESS focus outline to include all focused elements
Maintains and improves .focused class for ie8
Adds _globals to all popup models
Fixes button states, question view, notify and drawer to allow all to become accessible

Next stage is templates, components and extensions.

Had to resubmit  https://github.com/adaptlearning/adapt_framework/pull/527 < PR due to my fork going a bit funny. Apologies.

### CODE REVIEW

**Comment by moloko** [comment]
Did you spork instead of fork?

**Comment by moloko** [comment]
+1

**Comment by oliverfoster** [comment]
yea...

**Comment by taylortom** [comment]
+1
Looks good to me

**Comment by cgkineo-projects** [comment]
+1

**Comment by cgkineo-projects** [comment]
+1

**Comment by kirsty-hames** [comment]
+1

**Comment by dancgray** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by taylortom** [comment]
+1

**Comment by oliverfoster** [comment]
learning pool to review before pr as agreed on planning meeting.

**Comment by brian-learningpool** [comment]
+1

**Pull request merged**
