### PR TITLE
Adds support for _classes to NotifyPushView

### PR DESCRIPTION
**Pull request by brian-learningpool**

### CODE REVIEW

**Comment by moloko** [comment]
@lc-thomasberger do you mean do something more like
```
className: function () {
   return this.model.get('_classes');
}
```

**Comment by moloko** [comment]
@brian-learningpool while you're there it would be great if you could spare a minute to tidy up the poor indentation in the `render` function

**Comment by brian-learningpool** [comment]
@lc-thomasberger, I've converted `className` to a function and corrected the mix of tabs and spaces indentation by setting it to 4 spaces.

**Comment by moloko** [comment]
before I merge, did anyone test this change?

**Comment by oliverfoster** [comment]
i didn't, i just read it.

**Comment by moloko** [comment]
testing in FF and IE11 by running the following in the console:
```
Adapt.trigger('notify:push', { 
    title: "title",
    body: "message",
    _classes: 'some-class',
    _timeout: 30000
});
```

**Pull request merged**
