### PR TITLE
Accessibility fixes + updates

### PR DESCRIPTION
**Pull request by oliverfoster**
Fix for mac osx selected jump and for early operating system detection in accessibility.

https://github.com/adaptlearning/adapt-contrib-slider/pull/60

### CODE REVIEW

**Comment by moloko** [comment]
+1

**Comment by moloko** [comment]
oops

**Comment by dancgray** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by taylortom** [comment]
+1

**Comment by dancgray** [comment]
+1

**Pull request merged**
