### PR TITLE
Dependencies updated

### PR DESCRIPTION
**Pull request by hrajotia**
- **updated few core libraries:-**

| Library Name | Previous Version | Current Version |
| ----------------------- |:--------------------:|:--------------------:|
| backbone | 1.2.1 | 1.3.3 |
| bowser | 0.7.2 | 0.7.3 |
| handlebars | 2.0.0 | 4.0.5 |
| jquery | 1.11.2 | 1.12.3 |
| jquery.v2 | 2.1.3 | 2.2.3 |
| require | 2.1.17 | 2.2.0 |
| velocity | 1.2.2 | 1.2.3 |

- **updated npm modules:-**

| Module Name | Previous Version | Current Version |
| ----------------------- |:--------------------:|:--------------------:|
| chalk | 1.0.0 | 1.1.3 |
| columnify | 1.5.1 | 1.5.4 |
| grunt | 0.4.5 | 1.0.1 |
| grunt-concurrent | 2.1.0 | 2.3.0 |
| grunt-contrib-clean | 0.6.0 | 1.0.0 |
| grunt-contrib-connect | 0.8.0 | 1.0.2 |
| grunt-contrib-copy | 0.6.0 | 1.0.0 |
| grunt-contrib-handlebars | 0.9.2 | 1.0.0 |
| grunt-contrib-jshint | 0.12.0 | 1.0.0 |
| grunt-contrib-watch | 0.6.1 | 1.0.0 |
| grunt-jscs | 2.6.0 | 2.8.0 |
| grunt-jsonlint | 1.0.4 | 1.0.7 |
| grunt-replace | 0.11.0 | 1.0.1 |
| jit-grunt | 0.9.1 | 0.10.0 |
| jshint-stylish | 2.1.0 | 2.2.0 |
| less | 2.5.3 | 2.7.1 |
| load-grunt-config | 0.17.2 | 0.19.2 |
| requirejs | 2.1.22 | 2.2.0 |
| time-grunt | 1.2.1 | 1.3.0 |
| underscore | 1.6.0 | 1.8.3 |
| underscore-deep-extend | 0.0.5 | 1.1.4 |

### CODE REVIEW

**Comment by oliverfoster** [comment]
Awesome +1 :D thanks man!

**Comment by LukaszGrela** [comment]
+1

**Comment by brian-learningpool** [comment]
+1

**Comment by oliverfoster** [comment]
noo stop!

**Comment by oliverfoster** [comment]
the less library is broken

**Comment by oliverfoster** [comment]
ahh, hang on 2.7.1... let me just test a grunt dev

**Comment by oliverfoster** [comment]
2.7.0 was bust

**Comment by oliverfoster** [comment]
all perfect

**Pull request merged**
