### PR TITLE
Corrects #1152 with start controller functionality

### PR DESCRIPTION
**Pull request by brian-learningpool**
If the start controler is enabled, and '_force' is set to true, it should not be possible to route to the menu.

### CODE REVIEW

**Comment by moloko** [comment]
can I just check this wouldn't cause problems in a scenario where you're using _start to introduce an 'intro/sting' page before the menu?

**Comment by oliverfoster** [comment]
i think we need a isMenuDisabled property 

_force is meant to always start on the specified pages, it's not really meant to stop the menu.

**Comment by brian-learningpool** [comment]
@moloko, if you set `_force` to `false` in that case it will be possible to route to the menu. 

I agree with @oliverfoster though in that it might be better served with a new property to hide the menu.

**Comment by oliverfoster** [comment]
+1

**Comment by moloko** [comment]
+1
`_isMenuDisabled` will also need adding to [the documentation](/adapt_framework/wiki/Content-starts-with-course.json)

**Comment by brian-learningpool** [comment]
Documentation is now up to date.

**Comment by dennis-learningpool** [comment]
+1

**Pull request merged**
