### PR TITLE
Refactor app.js and adapt.js 

### LINKED ISSUE #2436: Adapt's 'entry point' code needs a big tidy-up
the code in app.js and adapt.js needs a serious tidy-up, it's way off the kind of coding standards we adhere to these days and, given that it's the 'entry point' into Adapt, it's confusing even to those of us who've been working with Adapt for years!

### PR DESCRIPTION
**Pull request by moloko**
This is a tidy for adapt.js and app.js. It introduces data.js which moves the data loading from app.js and adapt.js into its own file and provides a promised based wait mechanism for data ready waits.

add data.js and a `Promise` polyfill

resolves #2436

### CODE REVIEW

**Comment by moloko** [comment]
@oliverfoster the problem I'm stuck on is that, if you change language, `addNavigationBar` doesn't get run

**Comment by moloko** [comment]
@oliverfoster that's certainly solved that issue, thanks. I'll try and do a bit more testing over the next few days.

**Comment by oliverfoster** [comment]
cool, let me know. it all looks very nice at the moment :+1:

**Comment by oliverfoster** [comment]
nice catches

**Comment by moloko** [comment]
yep looking good, conflicts resolved and ready for review...

**Comment by moloko** [comment]
@oliverfoster I'm finding sporadic issues on iOS (v12.3.1) when running from an LMS - on relaunch it sometimes doesn't load properly. Tried so far from scorm_test_harness.html and SCORM Cloud. I'll do some more testing tomorrow to see if I can pin it down.

**Comment by oliverfoster** [comment]
cool, will have a look

**Comment by oliverfoster** [comment]
@moloko it was just that the data layer was finishing before spoor was able to listen for events.
I've stopped the data layer starting on initialize and allowed the app.js to start the data layer loading once it is assured that the plugins have all loaded and attached. This mimic the original behaviour where the data loader was inside the app.js and had already waited for all of the required libraries to load before starting the data load.

**Comment by oliverfoster** [comment]
@moloko is this good to go?

**Comment by moloko** [comment]
I haven't had a chance to re-test yet, it's next on my list.

I did wonder if we should put this in v5 rather than v4?

**Comment by oliverfoster** [comment]
I don't suppose it matters either way if it works in the AAT. All of the files we've changed are deep-core things which tend to get ignored and/or never overwritten and were mostly private to start with.

I think these are the only two publicly available functions which have changed location:
`Adapt.checkDataIsLoaded` > `Adapt.data.checkDataIsLoaded`
`Adapt.loadCourseData` > `Adapt.data.loadCourseData`

**Comment by moloko** [comment]
> I don't suppose it matters either way if it works in the AAT

I agree. My thinking was purely along the lines of that, although it's not a breaking change, it certainly is a pretty major change and so since v5 is now pretty close to being ready it might make more sense to bundle it with that.

**Comment by oliverfoster** [comment]
I you're happy it works and we can get it in? It'd be a shame to hold up v5 for it.

**Comment by moloko** [comment]
I'm hoping to retest it today so hopefully it shouldn't hold anything up

**Comment by moloko** [comment]
OK now working fine on iOS, cheers for that!

I can't approve this since I originally created the PR, but I'm happy it's good to go. I have tested it pretty extensively on IE11, Chrome, Firefox and Safari for iOS v12 (iPhone and iPad). I've done testing on:
* SCORM 1.2
* Multilanguage with:
 *  `_restoreStateOnLanguageChange` enabled
 *  `_restoreStateOnLanguageChange` disabled
 * one language having resources and the other not (to check the drawer icon disappears when not req'd
* Storing responses & resuming an assessment

Can anyone think of any other situations that would merit a test?

**Pull request merged**
