### PR TITLE
Fixes #516 - allows selection of specific menu

### LINKED ISSUE #516: Unable to select a specific menu when more than one is installed
Similar to theme selection, Gruntfile.js should be updated to allow support for selecting a specific menu when more than one is available.  As this is already implemented for themes I'm assuming this is an oversight for menu selection.

### PR DESCRIPTION
**Pull request by brian-learningpool**
This is very similar to a previous change for themes to allow
selection of a specific menu, when more than one is installed.

### CODE REVIEW

**Comment by oliverfoster** [comment]
+1 with amend to allow all menus to be included as before or a specific menu as per pr.

**Comment by oliverfoster** [comment]
```
            menuAssets: {
                files: grunt.file.expand(['src/extensions/<%= menu %>/']).map(function(cwd) {
                    return {
                        expand: true,
                        src: ['**'],
                        dest: '<%= outputdir %>build/assets/',
                        cwd: cwd + 'assets/',
                        filter: "isFile"
                    };
                })
            },
```

Can we try this out for the menuAssets?

**Comment by brian-learningpool** [comment]
It doesn't seem to work as expected.  Can this be raised as a new ticket?

**Comment by oliverfoster** [comment]
i'm alright with that as long as i can get a +1 with a multiple vs single implementation a bit later, this doesn't immediately affect us, but it will do when adapt is released

**Comment by oliverfoster** [comment]
i'd quite like to bring both themes and menus allowing both multiples and singles so that we can eventually have themes which switch out for accessibility and multiple menus depending on device +/ sub-menu requirements, they are awesome features it'd be nice to include.

**Comment by oliverfoster** [comment]
+1 as is.

**Comment by darylhedley** [comment]
+1

**Comment by brian-learningpool** [comment]
I agree with multiple menus and themes being a really nice feature but we should probably spend more time working out the exact requirements here.  

I've raised #520 regarding the hard-coded plugin names.

**Comment by dennis-learningpool** [comment]
+1

**Pull request merged**
