### PR TITLE
Add ability to insert variables into HTML files

### PR DESCRIPTION
**Pull request by Floppy**
In our theme, we want to add some course data into meta tags, etc, in a custom `required/index.html` file. 

Currently, in `required`, the XML files are processed so you can do things like this from https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/required/imsmanifest.xml#L9

```
 <langstring xml:lang="x-none"><![CDATA[@@course.title]]></langstring>
```

if we add `*.html` to the grunt replace job as well as `*.xml`, we should be able to do the same thing in index.html, meaning that themes can then automatically pull in data from the course. For instance:

```
 <title><![CDATA[@@course.title]]></title>
```

This is my first venture into the internals of the Adapt framework, so if there is a way I should be testing these jobs, or otherwise improving my PR, please tell me!

### CODE REVIEW

**Comment by moloko** [comment]
@Floppy thanks for this. I think this is a useful addition and may well help with issues like https://github.com/adaptlearning/adapt_framework/issues/1921

There's a guide to contributing to adapt [here](https://github.com/adaptlearning/adapt_framework/wiki/Contributing-code#submitting-your-code) that's worth a quick read - though really you're not far off, I think the only missing piece is that we normally require a matching Github issue for each PR. It's often worth logging this before you start the work to give people an opportunity to comment on what you'd like to do before you start work - this can help avoid re-work or you doing a lot of work submitting something that actually we don't think should be included.

**Comment by moloko** [comment]
@Floppy no, it's all good for this instance, particularly as you have given a comprehensive description of what is is you want to achieve and why

**Comment by Floppy** [comment]
Fantastic, thanks. When this is released I'll do a PR into the vanilla theme to add the course title into the header `title` tag, show how it's used :)

**Comment by Floppy** [comment]
Having checked the contributor guide first of course 😉

**Pull request merged**
