### PR TITLE
prevent handlebars error caused by ariaAnswer being undefined

### LINKED ISSUE #3089: FW 5.12.0 - (G)MCQ correct answer button triggers error if not using latest version of component
image

### PR DESCRIPTION
**Pull request by moloko**
if the relevant globals haven't been added to course.json - for example if using v4.0.1 (or earlier) of MCQ or v5.0.2 (or earlier) of GMCQ

fixes #3089

### CODE REVIEW

**Review by oliverfoster — APPROVED** [review]

**Review by tomgreenfield — APPROVED** [review]
:eye:

**Comment by tomgreenfield** [comment]
For posterity, an alternative with ternaries and early return (and guards for misconfiguration):
```js
getCorrectAnswerAsText() {
  const globals = Adapt.course.get('_globals')._components?.[`_${this.get('_component')}`];
  const isSingleSelect = this.isSingleSelect();
  const ariaAnswer = isSingleSelect ?
    globals?.ariaCorrectAnswer :
    globals?.ariaCorrectAnswers;
  if (!ariaAnswer) return;
  const correctOptions = this.getChildren().where({ _shouldBeSelected: true });
  const correctAnswer = isSingleSelect ?
    correctOptions[0]?.get('text') :
    correctOptions.map(correctOption => correctOption.get('text')).join('<br>');

  return Handlebars.compile(ariaAnswer)({ correctAnswer });
}
```

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by oliverfoster — APPROVED** [review]

**Review by tomgreenfield — APPROVED** [review]
Grudging :eye:

**Pull request merged**
