### PR TITLE
issue/1972: improved less compilation order

### PR DESCRIPTION
**Pull request by oliverfoster**
#1972 

1. The LESS files should be sorted by type. (no change)
2. Nested folders should compile after files, such that:
`src\theme\adapt-contrib-vanilla\less\src\*`
`src\theme\adapt-contrib-vanilla\less\src\custom\**`
Not:
`src\theme\adapt-contrib-vanilla\less\src\component.less`
`src\theme\adapt-contrib-vanilla\less\src\custom\**`
`src\theme\adapt-contrib-vanilla\less\src\drawer.less`
3. Longer filenames should always compile after shorter ones, only where the front matches
`src\extensions\adapt-contrib-trickle\less\trickle.less`
`src\extensions\adapt-contrib-trickle\less\trickle-button.less`
Not
`src\extensions\adapt-contrib-trickle\less\trickle-button.less`
`src\extensions\adapt-contrib-trickle\less\trickle.less`

### CODE REVIEW

**Comment by oliverfoster** [comment]
@chucklorenz is this what you had in mind?

**Comment by brian-learningpool** [comment]
Hi guys, can we hold fire on merging this for a little while?  I'd like @nilslp or @ciaranlp's input.

**Comment by oliverfoster** [comment]
Of course. Let me know when you've got an idea of the impact.
It's probably a good idea to test it.

**Comment by oliverfoster** [comment]
Good to go @brian-learningpool ?

**Comment by brian-learningpool** [comment]
All good, @oliverfoster. 👍

**Pull request merged**
