### PR TITLE
Add ability for server-build to generate source-maps

### LINKED ISSUE #733: server-build: add the option to create sourcemaps
See https://github.com/adaptlearning/adapt_authoring/issues/811

(logging here for quickness)

### PR DESCRIPTION
**Pull request by taylortom**
Fixes #733

### CODE REVIEW

**Comment by taylortom** [comment]
Also see https://github.com/adaptlearning/adapt_authoring/pull/857

**Comment by hrajotia** [comment]
+1

**Comment by oliverfoster** [comment]
+1

**Comment by moloko** [comment]
+1

**Pull request merged**
