### PR TITLE
New: partly correct aria labels added to course _globals (fixes #3565)

### LINKED ISSUE #3565: Create aria label for partly correct answers
### Subject of the enhancement
There is no aria label for partially correct question answers. See [original issue](https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/225#issuecomment-2147756370) raised. See existing labels below.

**course.json**
https://github.com/adaptlearning/adapt_framework/blob/917b16180a57a8ed3c492c99da4531910fb62660/src/course/en/course.json#L46-L47
https://github.com/adaptlearning/adapt_framework/blob/917b16180a57a8ed3c492c99da4531910fb62660/src/course/en/course.json#L62-L63

**buttonsView.js**
https://github.com/adaptlearning/adapt-contrib-core/blob/4b8a99ab60704bb6d6993992ceae575b86a120c7/js/views/buttonsView.js#L188-L194

### Expected behaviour
An aria label should exist for correct, partially correct and incorrect.

### PR DESCRIPTION
**Pull request by kirsty-hames**
Fixes https://github.com/adaptlearning/adapt_framework/issues/3565

### New
Partly correct aria labels added to course __globals_. 

Core [buttonsView](https://github.com/adaptlearning/adapt-contrib-core/blob/4b8a99ab60704bb6d6993992ceae575b86a120c7/js/views/buttonsView.js#L188-L194) to be updated to use  `answeredPartlyCorrect` aria label. Separate issue raised for core https://github.com/adaptlearning/adapt-contrib-core/issues/553

### CODE REVIEW

**Comment by cahirodoherty-learningpool** [comment]
@kirsty-hames Just a heads up that this needs an update

**Comment by oliverfoster** [comment]
I need to show you about merging branches @kirsty-hames

**Review by oliverfoster — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by joe-allen-89 — APPROVED** [review]
👍

**Pull request merged**
