### PR TITLE
Issue/#608

### LINKED ISSUE #608: Velocity library is really old and should be updated to the latest

### PR DESCRIPTION
**Pull request by darylhedley**
fixes #608 - tested across all core contributed plugins

### CODE REVIEW

**Comment by brian-learningpool** [comment]
+1 -- is this required on the develop branch too?

**Comment by darylhedley** [comment]
@brian-learningpool - na it's already been added there

**Comment by oliverfoster** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Pull request merged**
