### PR TITLE
Added ability to hide views using new isHidden attribute

### PR DESCRIPTION
**Pull request by ryanrolds**
While developing a [branching plugin](https://github.com/irisEd/adapt-irised-pathways) we needed a way to hide/unhide views.

### CODE REVIEW

**Comment by moloko** [comment]
do we want to add to v2 or leave for v3?

**Comment by moloko** [comment]
and now I think about it - do we want to add this to articleView as well for consistency?

**Comment by ryanrolds** [comment]
Derp, not sure how I missed `articleView`. I will take care of that in the morning.

**Comment by oliverfoster** [comment]
good catch

**Comment by ryanrolds** [comment]
Article issue corrected.

**Comment by moloko** [comment]
This needs adding to the Core Model Attributes wiki page - anyone got a minute to write me a brief description of this setting's purpose?

**Comment by moloko** [comment]
More importantly, it needs adding to the various .schema files so that it can be used in the authoring tool... leave that one with me.

**Comment by ryanrolds** [comment]
@moloko I will take care of this first thing when I'm back in the office next week (getting widsom teeth removed tomorrow).

**Pull request merged**
