### PR TITLE
Invalid CSS fix

### PR DESCRIPTION
**Pull request by andrewhosgood**
float:auto; -> float:none;

### CODE REVIEW

**Comment by belal-almassri-spongeuk** [comment]
+1 I wish if there is a css float:auto or gloat:random  :-).

**Comment by belal-almassri-spongeuk** [comment]
Can you make PR for the master as well please.

**Comment by hrajotia** [comment]
+1

**Comment by moloko** [comment]
+1
@belal-almassri-spongeuk we will be pushing develop > master very soon anyway so unless this is a critical fix, a separate PR to master isn't 100% necessary

**Pull request merged**
