### PR TITLE
Issue/#304

### LINKED ISSUE #304: Sort out plugin assets and how they compile into the build
- Plugins like spoor and media have assets and sometime might need grunt files run.
- Needs some research on best approach

### PR DESCRIPTION
**Pull request by hrajotia**
Fixes #304

### CODE REVIEW

**Comment by darylhedley** [comment]
+1

**Comment by oliverfoster** [comment]
[L252-261](https://github.com/hrajotia/adapt_framework/blob/feature/framework_dev_extension_assets/Gruntfile.js#L252-L261)

line 255 should really be at the bottom of the array making theme the overriding force of the assets folder also.

**Comment by hrajotia** [comment]
@oliverfoster nice suggestion :+1:

**Comment by darylhedley** [comment]
also assets as a general rule should be prefixed with plugin name to stop collisions of file names

**Comment by oliverfoster** [comment]
if we copied sub folders as well it wouldn't required prefixing but would allow for better organisation?

**Comment by taylortom** [comment]
+1

One suggestion (perhaps for another PR): I'd maybe like to see the watch run more fine-grained copy tasks rather than the entire copy:main.

**Comment by hrajotia** [comment]
@oliverfoster  and @taylortom - as per your suggestions I have made changes to assets `copy` task, now the assets folder structure would be maintained while copying them to build folder also I have segregated the `copy:main` task for components, extensions etc. which would make copying of assets light weight while watching them.

**Comment by moloko** [comment]
+1 - and I have tested this with the media component to make sure the assets folder (and subfolders) get copied over
@darylhedley when you say 'linked up', how do you mean?

**Comment by taylortom** [comment]
Confirmed working for me too. Don't seem to have the nested assets folder as requested by @oliverfoster though?

**Comment by hrajotia** [comment]
@taylortom -  could you please tell me how you've tested it?

**Comment by taylortom** [comment]
I misinterpreted what Ollie was suggesting. Going to open extra issues relating to this.

**Comment by hrajotia** [comment]
cool :+1:

**Comment by taylortom** [comment]
Are we to leave this open?
As there are some outstanding issues in #304 that still need discussion/implementation.

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt_framework/issues/210 also needs considering.

**Comment by oliverfoster** [comment]
+1 as is. The other items need bigger discussions.

**Comment by taylortom** [comment]
+1 
As per previous comment, let's split the further changes into new issue(s)/PR(s).

**Comment by moloko** [comment]
+1

**Pull request merged**
