### PR TITLE
Performance issues

### PR DESCRIPTION
**Pull request by oliverfoster**
Changed the _.each syntax for the for (var i = 0, len = x; i < len; i++) syntax,

<del>Removed backboneModel.js</del>
<br/>

Mapped Adapt._id attributes to stop findWhere / where operations for id's

### CODE REVIEW

**Comment by oliverfoster** [comment]
#507

**Comment by taylortom** [comment]
+1 for the concept, will test out when I get a min

**Comment by chuck-n0rr1s** [comment]
#513

**Comment by darylhedley** [comment]
-1 as it removes core functionality that hasn't been replaced. Our plugin architecture relies on this code

**Comment by oliverfoster** [comment]
Added core functionality back in.

**Comment by oliverfoster** [comment]
The plugin architecture does not rely on the previously removed code as removing it doesn't break anything and there are no direct dependencies upon it. No plugins we know of [so far] require or utilise the previously removed code either, hence the suggestion to remove it.

**Comment by dancgray** [comment]
Performance enhancements seem good, but having problems running this in IE8. Just hangs when trying to load pages, no errors. Admittedly it is a VM.

**Comment by oliverfoster** [comment]
missed variable uniqueness requirement should solve that daryl, was getting stuck in a fun loop

**Comment by dancgray** [comment]
+1

**Comment by taylortom** [comment]
+1, Noticeably faster in Win7 IE8

**Comment by moloko** [comment]
+1

**Pull request merged**
