### PR TITLE
issue-1163: moved vanilla font into core

### PR DESCRIPTION
**Pull request by oliverfoster**
https://github.com/adaptlearning/adapt_framework/issues/1163

### CODE REVIEW

**Comment by lc-thomasberger** [comment]
+1

**Comment by tomgreenfield** [comment]
There is probably now a good chance to drop a couple of the font formats before adding too much to core. According to [caniuse](http://caniuse.com/#feat=woff), WOFF is supported on:
* Chrome 5+
* Firefox 3.6+
* Internet Explorer 9+
* Edge
* Safari / iOS Safari 5.1+
* Chrome for Android (which runs on Android 4.1+)

We still need to keep the EOT version for Internet Explorer 8 but it looks safe to drop the **SVG** and **TTF** formats. In the future, we could discuss adding WOFF2 when it becomes more widely supported.

**Comment by guywillis** [comment]
+1

**Comment by tomgreenfield** [comment]
+1

**Comment by moloko** [comment]
+1

**Pull request merged**
