### PR TITLE
ACCESSIBILITY: Add latest jquery.a11y to libraries

### PR DESCRIPTION
**Pull request by oliverfoster**
Beginning of accessibility upgrade.

This is the inclusion of a general jquery accessibility plugin to help with global support of screen readers

Library: https://github.com/cgkineo/jquery.a11y 

@kirsty-hames @svenlaux

### CODE REVIEW

**Comment by oliverfoster** [comment]
Could everyone start reviewing this please?

**Comment by oliverfoster** [comment]
This is a fix for issues: #481 #476 #451 #443 #403

**Comment by dancgray** [comment]
Have been testing the accessibility pre-release over the last week and it seems to work really well. 

I have one question though. Has there been any consideration to how to deal with content that will be entered through a rich text editor?

The authoring tool will use a RTE to enter a lot of the text content and at best this is likely to have a lot of standard HTML markup (span, div, h1, ul etc) at worst it could contain non standard markup.

**Comment by olivermartinfoster** [comment]
On first thought that should be fine Dan. We often include a lot of HTML markup in our json here. There will probably be a few interesting ones that'll need ironing out though. I currently have a minor issue about how to treat <br> tags as they stop screen readers but have no content of their own. I'll elaborate further in an issue on jquery.a11y.

**Comment by dancgray** [comment]
+1

**Comment by lc-petranussdorfer** [comment]
+1

**Comment by oliverfoster** [comment]
Just checking that it is up to date with our latest ie8 changes before we merge. 2 ticks.

**Pull request merged**
