### PR TITLE
issue-1228-1: speed up javascript compilation

### PR DESCRIPTION
**Pull request by oliverfoster**
* moved all libraries out of compilation
* allowed all plugins to have a libraries folder
* allowed all plugins to have a required folder
* removed unneeded licensing comments

https://github.com/adaptlearning/adapt_framework/issues/1228

### CODE REVIEW

**Comment by tomgreenfield** [comment]
+1

**Comment by oliverfoster** [comment]
yea, enabling the plugins to have libraries for now, will allow us to move rangeslider and media-element into their rightful places as libraries. the sourcemapping / minification thing for them we'll have to sort out if it becomes a big issue.

**Comment by aniketdharia** [comment]
+1

**Comment by oliverfoster** [comment]
i missed bowser: new pr https://github.com/adaptlearning/adapt_framework/issues/1263

sorry

**Pull request merged**
