### PR TITLE
config: remove _shouldSupportLegacyBrowsers

### PR DESCRIPTION
**Pull request by akshay-bhavsar**
issue https://github.com/adaptlearning/adapt_framework/issues/1599

### CODE REVIEW

**Comment by moloko** [comment]
@sarveshwar-gavhane we will need to PR against the authoring tool as well for any changes to config.model.schema.

The framework only has copies of the core .schema files to allow the the `$ grunt translate:export` and `$ grunt translate:import` commands to work. The framework copies are not actually used by the authoring tool.

The authoring tool's copy of this file is [here](https://github.com/adaptlearning/adapt_authoring/blob/master/plugins/content/config/model.schema)

**Comment by sarveshwar-gavhane** [comment]
@moloko  i was thinking the same, but wasn't sure about this. @akshay-bhavsar can you raise PR there as well  ?

**Comment by akshay-bhavsar** [comment]
@sarveshwar-gavhane  Ok i will do it, thanks!

**Comment by oliverfoster** [comment]
we can't remove the lines in device.js, they're needed for styling

**Comment by akshay-bhavsar** [comment]
@oliverfoster  Ok!

**Comment by moloko** [comment]
@akshay-bhavsar changes to device.js need reverting...

**Comment by oliverfoster** [comment]
i this pr still live? can i close?

**Comment by akshay-bhavsar** [comment]
@oliverfoster yes, please close it.

**Comment by oliverfoster** [comment]
👍 thanks

**Pull request closed without merging**
