### PR TITLE
issue/3169 Moved src/core to adapt-contrib-core

### LINKED ISSUE #3169: adapt_framework: Move src/core to adapt-contrib-core
### Subject of the issue
In order to make Adapt truly pluggable, src/core should be moved to adapt-contrib-core this will help create a uniform plugin structure for moving away from [bower](https://bower.io/) to [npm](https://docs.npmjs.com/about-npm) for package management.

Connected to https://github.com/adaptlearning/adapt_framework/issues/2526

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #3169 

### Moved
* `src/core` moved to [adapt-contrib-core](https://github.com/adaptlearning/adapt-contrib-core) using [these instructions](https://medium.com/@ayushya/move-directory-from-one-repository-to-another-preserving-git-history-d210fa049d4b)

### Added
* `adapt-contrib-core` as a [git submodule](https://git-scm.com/docs/git-submodule) at `src/core`
* Script to ensure download and sync of `src/core` submodule on `npm install`

### Testing
Please download and test using (ticked systems have been tested):
- [x] AAT OSX
- [x] OSX
- [x] AAT windows
- [x] Windows (cmd and git bash)
- [x] AAT Linux
- [x] Linux

See file changes on branch [issue/3169](https://github.com/adaptlearning/adapt_framework/tree/issue/3169)
Choose branch issue/3169 on AAT installation.

### How it works
There is a new installation phrase the happens when `npm install` is executed. It downloads the submodules listed in `.gitmodules` and then ensures that they are set to the correct branch from [`gitmodules.js`](https://github.com/adaptlearning/adapt_framework/blob/f05785a47c5e058ead95f215061968e3d454382c/gitmodules.js). This change should be transparent on all systems.

### Why
We need to move from bower to npm for plugin management. By having all parts of the framework be installable plugins, it gives us much more freedom to swap and change pieces. `src/core` is the last part of Adapt Framework that should be a plugin (npm module in the future) everything else remaining in the repository (with the exception of the src/course folder - to be removed in v6) is necessary for building the associated plugins into a course.

### Notes
`src/core` is now a git repository inside of the adapt_framework git repository, to modify `src/core` it has its own `.git` folder independent of [`adapt_framework`](https://github.com/adaptlearning/adapt_framework) which pushes to [`adapt-contrib-core`](https://github.com/adaptlearning/adapt-contrib-core)

### CODE REVIEW

**Review by kirsty-hames — APPROVED** [review]
Tested on macosx.

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Comment by oliverfoster** [comment]
Tested in git bash, windows 10, by hand and with the aat

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Comment by oliverfoster** [comment]
Tested in cmd prompt windows 10, by hand and with the aat, export and preview work as expect

**Comment by oliverfoster** [comment]
Need to redo this adapt-contrib-core repo as bugfixes have gone into src/core since, please however carry on testing this pr.

**Review by eleanor-heath — APPROVED** [review]

**Comment by oliverfoster** [comment]
Tested on Ubuntu 20.04.2 AAT and terminal. Working fine.

**Review by guywillis — APPROVED** [review]
Tested on OSX AAT and successfully built

**Comment by oliverfoster** [comment]
Issue with update script on AAT run as root on linux.

`npm install` as executed by the AAT cannot run the `preinstall` npm script on the working directory as npm runs scripts without root privileges and the preinstall script needs write access on root folders. 

Issue detailed here https://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd/19132229#19132229

**Comment by oliverfoster** [comment]
@cahirodoherty-learningpool please check if this breaks adapt-builder

**Pull request merged**
