### PR TITLE
Refreshed existing and added new icons

### PR DESCRIPTION
**Pull request by guywillis**
Resolves https://github.com/adaptlearning/adapt_framework/issues/2688

* Refreshed visual appearance of existing icons - see issue for screenshots
* Added new icons - see issue for list + screenshot
* Updated icon references

### CODE REVIEW

**Comment by oliverfoster** [comment]
image love it, image nice refresh image a necessary piece of the puzzle image sets a nice... direction image

**Comment by chucklorenz** [comment]
Thanks for the refresh, Guy.
Two proposals:
1) a second set of block quotes. The current are quite round and serif-y. Would be nice to have an option that has a more minimalist and sans-serif look.
2) social media/networking logos. Both positive and negative images per each would help design. Which ones? The popular ones are obvious candidates. How many? Hard to say, but I'd encourage erring on the side of more than less. Many are available for free on IcoMoon. These may not seem too important to e-learning, but Adapt is being used in a broad manner. I used them in [adapt-aboutUs](https://github.com/chucklorenz/adapt-aboutUs) and even received a PR from samumist (Zheng Xu) to include some that are popular in China. My [selection.json](https://github.com/chucklorenz/adapt-aboutUs/blob/master/selection.json) in case it helps discussion.

**Comment by chucklorenz** [comment]
3. Wondering if we could get a series of 5 face emojis ranging from frown to smiling to use with slider/feedback situations

**Comment by chucklorenz** [comment]
Thanks for the additions! 
:+1:

**Pull request merged**
