### PR TITLE
issue/2939 remove placeholder alt text + update schema alt text description (take 2)

### PR DESCRIPTION
**Pull request by kirsty-hames**
...when adding a schema alt text 'title', the previous commit was reverted by accident https://github.com/adaptlearning/adapt_framework/pull/2953/files

### CODE REVIEW

**Review by moloko — APPROVED** [review]

**Comment by chucklorenz** [comment]
👍

**Review by oliverfoster — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by guywillis — APPROVED** [review]
👀

**Comment by tomgreenfield** [comment]
@kirsty-hames, could you start again with a fresh branch based off master please?

I believe the presence of the revert commit means the majority of your intended changes were not pulling through. I've tried merging master into this one but it hasn't helped.

**Pull request closed without merging**
