### PR TITLE
Change default behaviour to record interactions.

### PR DESCRIPTION
**Pull request by chris-steele**
https://adaptlearning.atlassian.net/browse/ABU-690

### CODE REVIEW

**Comment by belal-almassri-spongeuk** [comment]
+1, this needs to be changed on the master branch, it seems to be wrong there: 
        ``recordInteraction:function() {
            if (this.model.get('_recordInteraction') != false) {
                Adapt.trigger('questionView:recordInteraction', this, this.model.get('_recordInteraction') === true);
            }
        }``

**Comment by chris-steele** [comment]
Yes that's right, the correct form is:

if (this.model.get('_recordInteraction') === true || !this.model.has('_recordInteraction')) {
    Adapt.trigger('questionView:recordInteraction', this);
}

Apologies for making a bit of a hash of this!

**Comment by moloko** [comment]
@chris-steele not your fault, I was too slow with my review - I should have put a comment on the PR asking for it not to be merged until I'd had a chance to review properly

**Comment by moloko** [comment]
+1

**Comment by oliverfoster** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Pull request merged**
