### PR TITLE
Adding proper support for "_canShowFeedback"

### PR DESCRIPTION
**Pull request by jose-campos**

### CODE REVIEW

**Comment by oliverfoster** [comment]
Can you remove the _canShowFeedback switch? That switch is for later in the feedback process.
We still need feedback to be set if it's available and _canShowFeedback is false.

Just the check for `_feedback` should be sufficient here.

`_canShowFeedback` is a switch for this behaviour:
https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/views/questionView.js#L263-L267

**Comment by tomgreenfield** [comment]
Whole thing is well overdue a refactor, in the vein of this [comment](https://github.com/adaptlearning/adapt_framework/pull/1761#pullrequestreview-62768189).

**Comment by jose-campos-sr** [comment]
It seems that pull request is active, once someone with write access reviews it and fixes the conflicts I can go in and make the other changes mentioned.

**Comment by jose-campos** [comment]
It seems that pull request is active, once someone with write access reviews it and fixes the conflicts I can go in and make the other changes mentioned.

**Comment by amruta-thakur** [comment]
Hi @jose-campos 
While testing the above PR, I have observed one more issue that if we remove "_feedback" from the MCQ json and add the option specific "feedback" for each option then feedback doesn't appears. I have tested by both ways with adding your code and without adding the code, the issue arises. Can you please consider this scenario as well?

**Comment by tomgreenfield** [comment]
Note: with option-specific feedback, the `feedback` node should be present in the JSON anyway for the correct option.
```json
"_items": [
	{
		"text": "Correct option",
		"_shouldBeSelected": true
	},
	{
		"text": "Incorrect option",
		"_shouldBeSelected": false,
		"feedback": "Incorrect 1"
	},
	{
		"text": "Incorrect option",
		"_shouldBeSelected": false,
		"feedback": "Incorrect 2"
	}
],
"_feedback": {
	"title": "",
	"correct": "Correct"
}
```

**Comment by amruta-thakur** [comment]
@tomgreenfield : Thanks for the clarification.

**Comment by tomgreenfield** [comment]
Superceded by https://github.com/adaptlearning/adapt_framework/pull/2208.

**Pull request closed without merging**
