### PR TITLE
Allow ESC button to close the popup when accessibility is not active

### PR DESCRIPTION
**Pull request by belal-almassri-spongeuk**
Will allow ESC button to close the notification popup when the accessibility is not active rather than is not enabled!

### CODE REVIEW

**Comment by belal-almassri-spongeuk** [comment]
Thanks @oliverfoster

**Comment by oliverfoster** [comment]
+1

**Comment by andrewhosgood** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Pull request merged**
