### PR TITLE
issue/3080 Reverted to loading react via libraries folder

### LINKED ISSUE #3080: adapt_framework: v5.12.0 references node_modules directly
### Subject of the issue
Creating a separate inclusion pathway for react libraries from the standard `core/libraries` one, was a mistake. It has had some tooling issues across the community, from the AAT rewrite to clients to rub-cli.

Should revert to loading the react libraries through the standard libraries folder.

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #3080 

### Changes
* Reverted to loading react via libraries folder instead of from node_modules

### Tests
Working in IE11, Chrome, Firefox

### CODE REVIEW

**Review by tomgreenfield — APPROVED** [review]

**Review by moloko — APPROVED** [review]
tested in Firefox and IE11

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Comment by chris-steele** [comment]
I know this was a long while ago now, but I'm curious; what was the justification for this change?

**Comment by oliverfoster** [comment]
* AAT was installing the FW as a node_module and had conflicting node modules versions
* External dependencies don't get included properly from node_modules as adapt framework client-side compile isn't npm aware
* Didn't want react from parent tree node_modules to be included instead of the intended library

**Pull request merged**
