### PR TITLE
BUGFIX: safari + ipad duplicate elements

### PR DESCRIPTION
**Pull request by oliverfoster**
@zenduo

### CODE REVIEW

**Comment by belal-almassri-spongeuk** [comment]
:+1: Thanks Ollie this fixed the issue.

**Comment by zenduo** [comment]
+1

**Comment by oliverfoster** [comment]
duplicate elements were appearing on ipad if a  "<p>test hh dfg hdg hd</p>" was set as the article body

**Comment by dancgray** [comment]
Is this a specific version of iOS? I'm having a few issue reproducing.

**Comment by belal-almassri-spongeuk** [comment]
Hi Dan,

We noticed this issue on iPad IOS version 6.1.3, iPhone not sure of what version and on windows Safari(Not supported anymore), however we didn't notice it on Mac Safari.

**Comment by dancgray** [comment]
+1

**Pull request merged**
