### PR TITLE
issue/3007 Fixed aria-disabled click when a11y disabled

### LINKED ISSUE #3007: Disabled buttons can be clicked on
### Subject of the issue/enhancement/features
Disabled buttons are now operational when Accessibility is disabled.

Problem PR: https://github.com/adaptlearning/adapt_framework/pull/2951

### Your environment
Framework 5.8.1

### Steps to reproduce
1. In config.json:
```json
  "_accessibility": { "_isEnabled": false }
```
2. Click a disabled button on an unanswered question, for example.

### Expected behaviour
Clicking a disabled button should have no effect.

### Actual behaviour
Clicking a disabled button runs the code associated with that button.

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #3007 

#### Changed 
* Moved behaviour to prevent click behaviour above config check

### CODE REVIEW

**Review by moloko — APPROVED** [review]
code 👓

**Review by tomgreenfield — COMMENTED** [review]
You can also revert to the original [early return](https://github.com/adaptlearning/adapt_framework/pull/2951/files#diff-bdc6a376b558c7de28e9b7c14b38d8581e2724c6b427e1a3dda5a21dc15644c2L67).

**Comment by oliverfoster** [comment]
That flag is for an entirely different bit of behaviour. Have I fundmis something?

**Review by moloko — APPROVED** [review]
code 👓

**Review by tomgreenfield — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Pull request merged**
