### PR TITLE
re-added 'navigateToHomeRoute' function

### LINKED ISSUE #743: The router navigateToHomeRoute() function has been missed from v2
I'm not sure how this was missed but it needs to be added ASAP.

### PR DESCRIPTION
**Pull request by hrajotia**
Fixes #743

### CODE REVIEW

**Comment by brian-learningpool** [comment]
+1 -- thanks :+1:

**Comment by oliverfoster** [comment]
+1 -- what's it for?

**Comment by brian-learningpool** [comment]
It allows themes to have a 'home' button, which when clicked takes the user back to the home page.  The `backButton` handler only goes to the previous route, which can often mean multiple clicks before getting back to the menu.

**Comment by oliverfoster** [comment]
ahh, ok, so there are plans to use it, coool

**Comment by dancgray** [comment]
+1

**Pull request merged**
