### PR TITLE
Issue /1139

### PR DESCRIPTION
**Pull request by sarveshwar-gavhane**

### CODE REVIEW

**Comment by brian-learningpool** [comment]
Is this a breaking change?  How will this code now handle courses where these properties are still defined with the underscore?

**Comment by sarveshwar-gavhane** [comment]
can we do like this by adding or condition ??
var onLabel = Adapt.course.get('_globals') && (Adapt.course.get('_globals')._accessibility.accessibilityToggleTextOn || Adapt.course.get('_globals')._accessibility._accessibilityToggleTextOff);

**Comment by sarveshwar-gavhane** [comment]
@brian-learningpool  it is not breaking change, in old version of courses have older code

**Comment by brian-learningpool** [comment]
I was thinking of authoring tool users who upgrade the framework.

**Comment by sarveshwar-gavhane** [comment]
can i make the same changes in authoring tool model.schema will this be fine?

**Comment by brian-learningpool** [comment]
The changes should happen in the authoring tool course model.schema anyway, which will work for new courses going forward.  I think there's still an issue with existing ones though, unless you defensively code it, e.g. `accessibilityToggleTextOff || _accessibilityToggleTextOff`

**Comment by sarveshwar-gavhane** [comment]
yeah sure @brian-learningpool i have made the changes thanks !

**Comment by oliverfoster** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by chetan-hajare** [comment]
+1

**Pull request merged**
