### PR TITLE
Added a replace task to the end of grunt server-build

### PR DESCRIPTION
**Pull request by bell87**
Added a grunt config task called replace.

This makes use of [grunt-replace](https://www.npmjs.com/package/grunt-replace) npm library.

The task will replace any strings in xml files (prefixed with `@@`) with matching properties found in the course.json file.

### CODE REVIEW

**Comment by brian-learningpool** [comment]
Can you add this task to the `build.js` and `dev.js` tasks too?

**Comment by barry-learningpool** [comment]
+1

**Comment by oliverfoster** [comment]
can we try and support globs for the language folders, rather than using a single language?

is this complex enough for your needs? are you going to need to map the course structure from the json? or is a simple string replacement good enough for a standard xml?

**Comment by oliverfoster** [comment]
+1

**Pull request closed without merging**
