### PR TITLE
Resolves #636 - Corrects component _layout attribute issue

### LINKED ISSUE #636: Component "left" and "right" layout getting ignored on mobile when JSON does not match order
This issue was raised on the Adapt Authoring project but I believe it's due to a bug in `getChildren()` not treating 'left' as the 'first'.  There's more information on the original ticket here:
https://github.com/adaptlearning/adapt_authoring/issues/718

### PR DESCRIPTION
**Pull request by brian-learningpool**
This patch resolves the issue with precedence in that the ordering of the components.json could overide the _layout attribute.  This change assumes that a _layout of "left" should appear first.  In mobile views, if this was not handled in the theme this was not the case.

### CODE REVIEW

**Comment by moloko** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by taylortom** [comment]
+1
Could you also do a PR to develop please?

**Comment by brian-learningpool** [comment]
I've re-factored the code slightly to use the collection sort() method.  The PR for develop is here:
https://github.com/adaptlearning/adapt_framework/pull/638

**Comment by moloko** [comment]
+1

**Comment by oliverfoster** [comment]
+1

**Pull request merged**
