### PR TITLE
PLP and menu globals moved to plugin specific fields

### PR DESCRIPTION
**Pull request by dancgray**
PLP and menu globals match respective handlebars templates.

Also remove some redundant aria labels.

### CODE REVIEW

**Comment by oliverfoster** [comment]
Could you add in "visited": "Visited" to the globals bit? We seem to be using that a fair bit for accessibility. I think @guywillis wanted to include it at some point today.

**Comment by oliverfoster** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Pull request merged**
