### PR TITLE
ABU-1002: properties.schema globals defaults > course.json

### PR DESCRIPTION
**Pull request by oliverfoster**
https://adaptlearning.atlassian.net/browse/ABU-1002

### CODE REVIEW

**Comment by oliverfoster** [comment]
Yes it is. I've no idea how to do that. @taylortom can you fix?

**Comment by taylortom** [comment]
Yeah, I'll have a look

**Comment by oliverfoster** [comment]
cool ta

**Comment by oliverfoster** [comment]
boxmenu broken in dev branch until this gets in

**Comment by taylortom** [comment]
Note to self: remove all globals from course.json

**Comment by taylortom** [comment]
My changes are here: https://github.com/cgkineo-projects/adapt_framework/pull/2

**Comment by dancgray** [comment]
If I've read this right schema-defaults task will run every time and overwrite any user changes to globals made in course.json, which would not be so good.

**Comment by taylortom** [comment]
Have tested with my changes in the above PR, and and amends made in `src/course/` are carried across into `/build/`

**Comment by brian-learningpool** [comment]
+1

**Comment by taylortom** [comment]
+1

**Comment by lc-thomasberger** [comment]
+1

**Pull request merged**
