### PR TITLE
Added git action

### PR DESCRIPTION
**Pull request by NayanKhedkar**
#2793

Adding Github actions for checking the live version of the framework online using gh-pages
**Note:** variables(secrets) should be configured on Github
           1. USERNAME
           2. EMAIL
           3.  ACCESS_TOKEN

### CODE REVIEW

**Comment by oliverfoster** [comment]
Can you link to some documentation on how to get an access_token etc?

**Comment by NayanKhedkar** [comment]
Sure @oliverfoster 

https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line#creating-a-token

https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#:~:text=Creating%20encrypted%20secrets%20for%20a%20repository,-To%20create%20secrets&text=To%20create%20secrets%20for%20an,the%20left%20sidebar%2C%20click%20Secrets.

**Comment by oliverfoster** [comment]
Thanks.

**Comment by oliverfoster** [comment]
closing as stale

**Comment by cahirodoherty-learningpool** [comment]
Hi @oliverfoster, I see you've decided to open this up again. Can I ask what you're intending?

I would love for our Core updates to trigger a FW PR automatically, but will only raise it as an issue if it doesn't step on the toes of this.
Thanks

**Comment by oliverfoster** [comment]
Yea, I was just wondering if it's useful to publish the vanilla course onto a gh page. Thoughts?

**Comment by cahirodoherty-learningpool** [comment]
Yeah cool with me.
So is that a publish per FW version or just override with latest each time?

Is this a precursor to automated testing in any way? Or just a quick resource to point to for manual checking of stuff?

**Comment by cahirodoherty-learningpool** [comment]
@oliverfoster I think this can be shut down now that the testing branch has gone in to FW

**Comment by cahirodoherty-learningpool** [comment]
No longer needed

**Pull request closed without merging**
