### PR TITLE
fixes for #895

### LINKED ISSUE #895: Make resources drawer tabbing cycle more logical
Current resources drawer tabbing cycle is as follows:
Back button
Close drawer button
View all resources button, etc.

It has been suggested that we change to the following:
Back button
View all resources button, etc.
Close drawer button

Originally reported by Sam Cook 26/Jun/15 4:48 PM

Moved from [ABU-823](https://adaptlearning.atlassian.net/browse/ABU-823)

### PR DESCRIPTION
**Pull request by sarveshwar-gavhane**
Fixes #895

### CODE REVIEW

**Comment by sarveshwar-gavhane** [comment]
https://github.com/adaptlearning/adapt_framework/issues/895

**Comment by brian-learningpool** [comment]
+1

**Comment by lc-thomasberger** [comment]
+1

**Comment by oliverfoster** [comment]
quote from github:

@sarveshwar-gavhane can you try it by putting the toolbar/close button last in the dom order, and restyling to push the toolbar/close button back to the top? the code you've done isn't guarenteed to work all of the time. it is just a quirk of the jquery.a11y implementation and not a defined behaviour. notify and hotgraphic are both done in 'dom order' style so it'd be more uniform... if it's not too much to ask?

i'm not sure how your implementation will work on ipad either, which doesn't use tab indexes, but does use dom order.

**Comment by oliverfoster** [comment]
alternative implementation: https://github.com/adaptlearning/adapt-contrib-vanilla/pull/191

**Comment by moloko** [comment]
done  via https://github.com/adaptlearning/adapt-contrib-vanilla/pull/191 - don't need this anymore

**Pull request closed without merging**
