### PR TITLE
Turn browserstring into valid css classes

### PR DESCRIPTION
**Pull request by lc-thomasberger**
- replace "." with "-"
- convert to lowercase

Old syntax kept in to maintain backwards compatibility.

### CODE REVIEW

**Comment by oliverfoster** [comment]
can you keep the old syntax as well so it's not breaking?

**Comment by lc-thomasberger** [comment]
sure @oliverfoster

**Comment by brian-learningpool** [comment]
Is the old syntax actually required?  As far as I'm aware CSS is case insensitive so `os-windows` should work fine.  For version-56.0 to actually have ever worked it would have required some backslash escaping in the CSS.

**Comment by tomgreenfield** [comment]
+1 for backwards compatibility @oliverfoster, I have been using (escaped) version classes in CSS for various plugins.

**Comment by oliverfoster** [comment]
I'm not sure we can remove supported syntax for selectors without notifying the community.

**Pull request merged**
