### PR TITLE
Added init function back in

### LINKED ISSUE #499: this.init is not called in adaptModel.js

### PR DESCRIPTION
**Pull request by darylhedley**
This enables componentModel.js to setup _isQuestionType
fixes #499

### CODE REVIEW

**Comment by brian-learningpool** [comment]
+1 -- how/when was this removed though?

**Comment by darylhedley** [comment]
I remember removing because there was an issue - I may have been guilting of not checking what it did

**Comment by moloko** [comment]
https://github.com/adaptlearning/adapt_framework/commit/97b82861562ecdeb2701dcc603e94f29746d94e3

**Comment by moloko** [comment]
+1
If you use [this package.json](https://github.com/adaptlearning/adapt_framework/blob/a3e4434d086befbe54c5a33128e2be261a6a6ee4/package.json) the Travis CI build should work

**Comment by darylhedley** [comment]
The compared changes in that package.json to the current one is a line added

**Comment by hrajotia** [comment]
+1

**Comment by taylortom** [comment]
+1

**Comment by moloko** [comment]
sorry, I linked to the wrong thing - should be these changes: https://github.com/hrajotia/adapt_framework/commit/4299c43f40fea8881a92be5b364de55e8cf687a7 (that's what worked for @hrajotia anyway)

**Pull request merged**
