### PR TITLE
Added math helper

### PR DESCRIPTION
**Pull request by oliverfoster**
https://github.com/adaptlearning/adapt_framework/issues/556

### CODE REVIEW

**Comment by oliverfoster** [comment]
@LukaszGrela

**Comment by moloko** [comment]
+1

**Comment by LukaszGrela** [comment]
+1:)

**Comment by hrajotia** [comment]
:+1: 
FYI -
```
{{#each arrayItems}}
    {{math @index "+" 1}}
{{/each}}
```

**Pull request merged**
