### PR TITLE
Resolves #969, corrects loop bug in Grunt getIncludes() helper

### LINKED ISSUE #969: Bug in Grunt helpers.js, in getIncludes()
The two `count` variables here can cause problems with the outer loop.

### PR DESCRIPTION
**Pull request by brian-learningpool**
Two 'count' variables were causing a problem with the loop.

### CODE REVIEW

**Comment by taylortom** [comment]
+1

**Comment by bell87** [comment]
+1

**Comment by dennis-learningpool** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by moloko** [comment]
Now we're requiring node 4.3 as a minimum we could presumably start using `let` instead of `var` as a way of avoiding issues like this

**Comment by brian-learningpool** [comment]
Yes, we could.

**Pull request merged**
