### PR TITLE
Modified code in setupPartlyCorrectFeedback

### PR DESCRIPTION
**Pull request by sarveshwar-gavhane**

### CODE REVIEW

**Comment by moloko** [comment]
thanks for the update, just been testing and have found that if you:
* don't have partly correct feedback set
* have `_attempts` set to 2 (or more)
* have 'notFinal' incorrect feedback set
* get the question partly correct on the first attempt
Then the 'final' incorrect feedback is set rather than than the 'notFinal', which is what I would expect.

Would it not be better to call `setupIncorrectFeedback()` whenever there isn't appropriate `_partlyCorrectFeedback` set? i.e. instead of lines 415 - 418?

**Comment by moloko** [comment]
Replacing lines 415 - 418 with
`this.setupIncorrectFeedback();`
Seems to solve the problem for me

**Comment by sarveshwar-gavhane** [comment]
okay thats great.... :)

**Comment by moloko** [comment]
+1

**Comment by brian-learningpool** [comment]
+1

**Comment by oliverfoster** [comment]
+1

**Pull request merged**
