### PR TITLE
Add support for swipe events

### PR DESCRIPTION
**Pull request by danielstorey**
This makes #1596 possible whilst also making swipe events available for other plugins to use, rather than adding an exclusive dependency just for narrative.

Note this update does not directly add swipe functionality to the Narrative component.

This file was compiled using the custom download build and contains just the code needed for touch/swipe events. Other jQuery mobile modules are therefore not included.

See http://api.jquerymobile.com/category/events/ for usage

### CODE REVIEW

**Comment by oliverfoster** [comment]
can we have an unminified version?

**Comment by danielstorey** [comment]
There you go!

**Comment by oliverfoster** [comment]
ta vm.

**Comment by oliverfoster** [comment]
where did you get this from? @danielstorey can i have a source reference before we merge it?

**Comment by danielstorey** [comment]
http://jquerymobile.com/download-builder/

Select **Touch** under **Events** then **Build My Download**

**Comment by oliverfoster** [comment]
cool, it's a shame there's not permanent link to it.
it it worth putting a comment at the top with the url it came from and what was selected?

**Comment by sarveshwar-gavhane** [comment]
yes it is there are so many modules to select.

**Comment by danielstorey** [comment]
Yeah it is a shame. The only permanent links would be to the full library which is 196Kb. This version is only 8Kb! The good thing is though jQuery allow custom downloads from each branch so it'll always be accessible via the builder in the link above. I've added instructions and also renamed the file to the original name of the downloaded file, to avoid any confusion

**Pull request merged**
