### PR TITLE
Reverts #1095

### PR DESCRIPTION
**Pull request by brian-learningpool**
This allows loading.hbs in the theme to set the loading content.

### CODE REVIEW

**Comment by andrewhosgood** [comment]
+1

**Comment by oliverfoster** [comment]
+1
did we still want an early loading screen?
one that at least gives an indication of something before the styled loading screen appears?

**Comment by moloko** [comment]
@oliverfoster yes definitely

**Comment by brian-learningpool** [comment]
I agree, and I've re-opened https://github.com/adaptlearning/adapt_framework/issues/1095.

**Pull request merged**
