### PR TITLE
modified to resolve issue #1073

### PR DESCRIPTION
**Pull request by chetan-hajare**

### CODE REVIEW

**Comment by moloko** [comment]
This is working great and I think we now have the right structure - my only remaining issue is with the name `disableFeedbackButton` - because that's not really what this code is doing - it's the theme that actually does that.

I'm thinking either `addNoFeedbackClasses` - or maybe better to have a more generic name `addClasses` so that this could be extended by plugins... @brian-learningpool any thoughts?

**Comment by brian-learningpool** [comment]
I think naming the function `checkFeedbackState()`instead might work better.   This would be more in line with the existing `checkResetSubmittedState()`, which does something similar.

Also, mind the spacing.

**Comment by moloko** [comment]
plus maybe an explanatory comment above line 115 explaining that the purpose is to allow the feedback button to be hidden and the submit button to stretch to fill the space - and that the CSS for this is in the theme

**Comment by oliverfoster** [comment]
+1

**Comment by brian-learningpool** [comment]
@chetan-hajare, are you ok to rename the function to `checkFeedbackState()`?  

It'd be great to get this into the next release.

**Comment by oliverfoster** [comment]
@chetan-hajare this one went in on a separate pr just after you changed it this morning (https://github.com/adaptlearning/adapt_framework/pull/1171), sorry, thanks for doing the hard work. 
could you close this?

**Comment by chetan-hajare** [comment]
Sure, and sorry I made the changes late.

**Comment by oliverfoster** [comment]
nah don't worry, learningpool needed the change quicker than we'd normally expect. it's not your fault. 19 hours is a reasonable time between a request and an update. we've often have changes that take weeks to implement.

**Comment by brian-learningpool** [comment]
Many thanks for your PR, @chetan-hajare.  This is a really good enhancement.

**Pull request closed without merging**
