### PR TITLE
correct typo in icons.less

### LINKED ISSUE #2959: typo in icons.less
typo: [.icon-exlcamation](https://github.com/adaptlearning/adapt_framework/blob/bb5e71e1c5a7c0e0770e0c3b2738445a10d99b6e/src/core/less/_defaults/icons.less#L176)

[src/core/less/_defaults/icons.less](https://github.com/adaptlearning/adapt_framework/blob/bb5e71e1c5a7c0e0770e0c3b2738445a10d99b6e/src/core/less/_defaults/icons.less#L176)

### PR DESCRIPTION
**Pull request by chucklorenz**
resolves #2959 

changed .icon-exlcamation to .icon-exclamation

### CODE REVIEW

**Review by moloko — APPROVED** [review]

**Review by tomgreenfield — APPROVED** [review]
This makes me `.icon-emotion-very-happy`.

**Comment by guywillis** [comment]
I think you'll also need to update the fonts and selection.json too as if they get imported into Icomoon they'll contain the class typo.

**Comment by chucklorenz** [comment]
@guywillis on it!

**Comment by chucklorenz** [comment]
FYI- Large numbers of changes appear in selection.json. Apparently icomoon is generating json props in a slightly different order. Only 2 changes made by me: fixed typo and incremented minor version from 0 to 1.

**Review by guywillis — APPROVED** [review]
👍

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by moloko — APPROVED** [review]

**Pull request merged**
