### PR TITLE
reset _isStarted on language change

### PR DESCRIPTION
**Pull request by moloko**
fixes https://github.com/adaptlearning/adapt_framework/issues/2977

### CODE REVIEW

**Comment by moloko** [comment]
@oliverfoster better?

**Review by oliverfoster — APPROVED** [review]

**Comment by oliverfoster** [comment]
Noice. Does it work?

**Comment by moloko** [comment]
it certainly fixes the issue for me - and doesn't appear to cause any knock-on effects... but then I'm only testing one aspect of it and not its use in more advanced stuff like you mention [here](https://github.com/adaptlearning/adapt_framework/issues/2977#issuecomment-731195034)

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by eleanor-heath — APPROVED** [review]

**Pull request merged**
