### PR TITLE
Issue ABU-799

### PR DESCRIPTION
**Pull request by sarveshwar-gavhane**
Fixes [ABU-799](https://adaptlearning.atlassian.net/projects/ABU/issues/ABU-799)

### CODE REVIEW

**Comment by hrajotia** [comment]
+1

**Comment by oliverfoster** [comment]
+1 oh yes!

**Comment by moloko** [comment]
+1

**Comment by moloko** [comment]
remember, no merging of PRs in adapt_framework until the sprint is closed...

**Comment by brian-learningpool** [comment]
+1

**Pull request merged**
