### PR TITLE
issue-1164: moved theme common assets to core

### PR DESCRIPTION
**Pull request by oliverfoster**
https://github.com/adaptlearning/adapt_framework/issues/1164

* allows core to have assets
* adds ie8 transparency pngs and loading gif to core

### CODE REVIEW

**Comment by lc-thomasberger** [comment]
+1

**Comment by guywillis** [comment]
+1

**Comment by tomgreenfield** [comment]
+1

**Comment by moloko** [comment]
Can I just check that if you have a different ajax-loader.gif in your theme, that would be used instead?

**Comment by oliverfoster** [comment]
Yes @moloko, the core assets task is the first one to run. All others override.

**Comment by moloko** [comment]
+1

**Pull request merged**
