### PR TITLE
Stop all body text being selectable

### PR DESCRIPTION
**Pull request by oliverfoster**
fix to prevent accidental selection of text on touch devices.

### CODE REVIEW

**Comment by moloko** [comment]
+1
which reminds me, should we not include some kind of no-prefix add-on for LESS in the framework?

**Comment by oliverfoster** [comment]
Wise plan. Got on in mind?

**Comment by moloko** [comment]
I know little of such things, might be best to check with a front end expert. http://lessprefixer.com/ looks like it might be OK though?

**Comment by taylortom** [comment]
Excellent suggestion

**Comment by taylortom** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by tomgreenfield** [comment]
I think there's a valid use case for being able to highlight and copy text out of Adapt courses. A learner may wish to paste content into another piece of software to take notes, copy terms into a Google search, or paste a hyperlink into a different browser, to name a few examples. It's also useful for reviewers who request amends to the course to be able to grab chunks of text from the page.

At the very least, could we consider re-enabling on desktop browsers? I'd be happy to hear your thoughts.

**Comment by oliverfoster** [comment]
+1 @tomgreenfield

**Comment by moloko** [comment]
ah right, I assumed this was for touch devices only - agree with @tomgreenfield

**Comment by taylortom** [comment]
Thinking this over again, and in support of @tomgreenfield, I think that this can be valuable even for mobiles. Can we have an option to disable this, rather than turning it off by default? Can't speak for iPhone, but as an android user, I've come to expect *long-click-to-select-text* pretty much everywhere (web and apps), so not being able to do this seems odd.

**Comment by dancgray** [comment]
I also agree with @tomgreenfield, if we are going to to turn it off can we have the option to disable.

**Comment by oliverfoster** [comment]
How about this one > https://github.com/adaptlearning/adapt_framework/pull/634

**Pull request merged**
