### PR TITLE
Closes ABU-466 (for v2 release)

### PR DESCRIPTION
**Pull request by zenduo**
I've done this in prep for release, no need to merge right now.

https://adaptlearning.atlassian.net/browse/ABU-466

### CODE REVIEW

**Comment by taylortom** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by lc-thomasberger** [comment]
+1

**Comment by zenduo** [comment]
Merge on the day of release.

**Comment by taylortom** [comment]
Done manually.

**Pull request closed without merging**
