### PR TITLE
various fixes

### PR DESCRIPTION
**Pull request by hrajotia**
- included extension assets
- theme should be at last position while concatenating less files.
- updated the way spoor's required folder content copied to build folder

### CODE REVIEW

**Comment by darylhedley** [comment]
+1

**Comment by oliverfoster** [comment]
Looks good, are lines 110-111 and 267 essentially the same thing?

**Comment by oliverfoster** [comment]
Can we have menu assets as well whilst we're at it?

**Comment by darylhedley** [comment]
+1 for menu assets too

**Comment by hrajotia** [comment]
@darylhedley i'm onmy way!!
@oliverfoster yeah they are but the first one is for copying assets and second one is for watch task!!
also i'll add menu assets too..

Thanks :)

**Comment by oliverfoster** [comment]
I was thinking about having the required folder menu/theme/etc applicable as a way to add loading pages etc as extensions. it'd possible need to copy folders as well as files, but it would essentially be a roots version of assets (but with folder copies as well).

Speaking of which, assets sub folders would be nice too.

**Comment by brian-learningpool** [comment]
+1, nice fix on the theme LESS processing.  That was causing some issues.  

Is Travis broken again though?

**Comment by oliverfoster** [comment]
nah, this is a pr to the master brian

**Comment by hrajotia** [comment]
@brian-learningpool yeah may be dependencies failing!!

**Comment by moloko** [comment]
the PR is set to merge into master, that's probably why the Travis CI build is failing. Always seems to when you do that.
@hrajotia  did you meant to merge into master?

**Comment by hrajotia** [comment]
@moloko yeah we have to add the assets of extension and menus so i have to made two PRs for both master and dev branch!!

**Comment by oliverfoster** [comment]
is this really necessary to have in the current master? in a month or so master will be updated to the develop changes anyway, as per the release schedule.

**Comment by darylhedley** [comment]
This is a bug and should be done as a hotfix like himanshu has done

**Comment by oliverfoster** [comment]
i seeee. cool. looks like the need a few ~ characters by the version numbers in the package.json

**Comment by moloko** [comment]
+1

**Comment by brian-learningpool** [comment]
This PR has three +1s, are we OK to merge?

**Comment by moloko** [comment]
fine by me

**Pull request merged**
