### PR TITLE
ABU-736: Moved contributor list to package.json

### PR DESCRIPTION
**Pull request by taylortom**
Fixes https://adaptlearning.atlassian.net/browse/ABU-736

Also quite a few whitespace amends as a result of saving the files in my editor (trailing spaces, tabs on empty lines etc. etc.).

### CODE REVIEW

**Comment by zenduo** [comment]
+1, although there are conflicts showing for this commit, e.g. no auto merge.

**Comment by zenduo** [comment]
+1 looking good now

**Comment by zenduo** [comment]
@taylortom hit me up on skype if you are on alan.bourne.spongeuk

**Comment by belal-almassri-spongeuk** [comment]
+1

**Comment by taylortom** [comment]
**DO NOT MERGE THIS YET PLEASE** :grin:

**Comment by taylortom** [comment]
If I've missed anyone out of the package.json, comment here, and I'll add them.

**Comment by moloko** [comment]
+1
this shouldn't prevent this from going through but you might just want to check with Gav if he wants his name on here given that he doesn't work on this any more (SPLITTER!)

**Comment by zenduo** [comment]
+1

**Comment by oliverfoster** [comment]
+1

**Pull request merged**
