### PR TITLE
Accessibility integration

### PR DESCRIPTION
**Pull request by oliverfoster**
Traps tab on accessibility button if accessibility isn't on
Adds accessibility instructions for screen readers
Fixes popupmanager and tabindexes on popup/popdown
Wraps tab around to top of page from the bottom
Integrates jquery.a11y into the handlebars templates so that text blocks can become tabbable
Adds accessibility state rendering to componentView (is currently missing the 'state' partial as it needs to be added to theme)
Allows aria-labels to be read across all devices
Expands LESS focus outline to include all focused elements
Maintains and improves .focused class for ie8
Adds _globals to all popup models
Fixes button states, question view, notify and drawer to allow all to become accessible

Next stage is templates, components and extensions.

### CODE REVIEW

**Comment by oliverfoster** [comment]
Directly fixes: #443 #476

**Comment by oliverfoster** [comment]
Tested working in chrome41, ie8 and safari on ios 7.1.2

**Comment by moloko** [comment]
+1. quick check done in IE8 & 9, FF 35, Chrome and - just for fun - Opera

**Comment by oliverfoster** [comment]
err, going to have to redo this

**Comment by oliverfoster** [comment]
apologies

**Pull request closed without merging**
