### PR TITLE
Changing config variable set by lang param

### PR DESCRIPTION
**Pull request by cahirodoherty-learningpool**
Resolves [#3227](https://github.com/adaptlearning/adapt_framework/issues/3227)

### CODE REVIEW

**Review by oliverfoster — APPROVED** [review]

**Comment by oliverfoster** [comment]
You could perhaps do this in the language picker as well. Check for a lang param and skip the loading process.

**Review by eleanor-heath — APPROVED** [review]

**Comment by oliverfoster** [comment]
I haven't gotten a handle on the consequences of changing `_activeLanguage` here as it's associated with a series of event listeners I believe, I'm not sure if this is early enough to make no difference or if it works as expected. Can you give a fuller explanation of how this doesn't impact the loading process with some permalinks etc and ensure to test it with the language picker and without the language picker and with an invalid language code before it gets merged?

**Comment by cahirodoherty-learningpool** [comment]
Single language course: [demo](https://cloud.scorm.com/content/courses/J2069IIUXH/single-language-course19ef4ea5-1c9b-42f6-ac22-7d77f5529415/0/index.html?actor=%7B%22name%22%3A%5B%22a%20a%22%5D%2C%22account%22%3A%5B%7B%22accountServiceHomePage%22%3A%22http%3A%2F%2Fcloud.scorm.com%22%2C%22accountName%22%3A%22J2069IIUXH%7Ca%40a.com%22%7D%5D%2C%22objectType%22%3A%22Agent%22%7D&endpoint=https%3A%2F%2Fcloud.scorm.com%2Flrs%2FJ2069IIUXH%2F&auth=Basic%20OjM4NjdjMzAxLTRjZjctNDRhNS04OGY0LWM0Y2M3OTkzOWNmNw%3D%3D&content_token=94681177-b781-474c-8ee0-028b2a3ed75b&externalRegistration=KTIMHSkw1_Zk91kqCy8xH2iZYk-MgctuIeFAYsJdcoL4muFPy-tUdNLBs0JPqTqwMyLvSWXsrNMZd96tDaXRZGiKdHpNXK7jj3IOCu8910j9lQA9vCvdCyIPA9nyM48&activity_id=https%3A%2F%2Fwww.learningpool.com&registration=9dc595a4-f42e-4065-a774-5c88abccacbe&externalConfiguration=ncwIgzSLkaBsNy2KDZ4YLvSfqIpit-80w6Lk8Sy0_kimpoiPH7kRFHeVdK7BvMxdAZ7vUKCp94TZzH4Wck8XpP-q5MK0tRYTxQ&grouping=https%3A%2F%2Fwww.learningpool.com&content_endpoint=https%3A%2F%2Fcloud.scorm.com%2Flrs%2FJ2069IIUXH%2Fcontent%2F&width=988&height=724&left=466&top=0)
Passing any lang param has no bearing on the course
_activeLanguage will  not be set in configModel.js - Adapt.build.get('availableLanguageNames') will only include the _defaultLanguage

Multi language course: [demo](https://cloud.scorm.com/content/courses/J2069IIUXH/multi-language-coursea5df6617-1111-4952-ace1-035768af9c73/0/index.html?actor=%7B%22name%22%3A%5B%22C%20T%22%5D%2C%22account%22%3A%5B%7B%22accountServiceHomePage%22%3A%22http%3A%2F%2Fcloud.scorm.com%22%2C%22accountName%22%3A%22J2069IIUXH%7Ccahir.odoherty%40learningpool.com%22%7D%5D%2C%22objectType%22%3A%22Agent%22%7D&endpoint=https%3A%2F%2Fcloud.scorm.com%2Flrs%2FJ2069IIUXH%2F&auth=Basic%20OjVkOTNmYmUzLTM4OTItNGIwMC04MmQxLTM1NzQ3ZDNjMWI3ZA%3D%3D&content_token=c742129d-7074-41d4-a8f1-13184a186656&externalRegistration=K9JLtVbCZKs2fcDJmWrW6vYQdml-mMierAQgpEBXOlMSQ8SgzaZuRRujZQhtwEsD9ccxi1_iwssHwDP2zaF90CATbni_BHWx7hD2WoOnHvKCljRMJ-rlVabKzh6JKbA&activity_id=https%3A%2F%2Fwww.learningpool.com&registration=bfaf94c5-c74e-442d-b6fe-e8bdcc82cb23&externalConfiguration=v7kv0FPJVJibafpMGJlCZ60ICUuKL9Gsxy3BEmTZlYpsqB0Ea_rBBpfbgFSvcb6g0bxqNOrG4CqNRXrMRefwjP8T7jM8IrRJ2g&grouping=https%3A%2F%2Fwww.learningpool.com&content_endpoint=https%3A%2F%2Fcloud.scorm.com%2Flrs%2FJ2069IIUXH%2Fcontent%2F&width=988&height=724&left=466&top=0) (add &lang=<ANY> at the end. supported languages are 'de', 'en' and 'fr')
Passing any lang param sets the _activeLanguage provided it is in Adapt.build.get('availableLanguageNames').
configModel: is triggered as usual, causing onLoadCourseData in data.js. As _activeLanguage is already set, the course data is loaded (no early return). It does not require the typical trigger that happens from onLanguageChange fired by the languagePicker

Tested with these scenarios in mind and working as expected

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt_framework/blob/db04181be6880ffd2ca3a882002014ced9e41452/src/core/js/data.js#L45-L52

https://github.com/adaptlearning/adapt_framework/blob/db04181be6880ffd2ca3a882002014ced9e41452/src/core/js/models/configModel.js#L38-L56

https://github.com/adaptlearning/adapt_framework/blob/db04181be6880ffd2ca3a882002014ced9e41452/src/core/js/models/configModel.js#L22-L36

https://github.com/adaptlearning/adapt-contrib-languagePicker/blob/8ee25105eb9a6cfeaa548c7a63ef97591dcec708/js/adapt-languagePicker.js#L19-L27

```js
  function onConfigLoaded() {
    if (!Adapt.config.has('_languagePicker')) return;
    if (!Adapt.config.get('_languagePicker')._isEnabled) return;

    Adapt.config.set('_canLoadData', false);

    languagePickerModel = new LanguagePickerModel(Adapt.config.get('_languagePicker'));

    Adapt.on('router:menu router:page', setupNavigationView);
```
https://github.com/adaptlearning/adapt_framework/blob/db04181be6880ffd2ca3a882002014ced9e41452/src/core/js/data.js#L74-L83

https://github.com/adaptlearning/adapt_framework/blob/db04181be6880ffd2ca3a882002014ced9e41452/src/core/js/data.js#L66-L72


It looks like rather than by-passing the language picker, they both act in tandem, the language picker renders and then gets navigated away shortly thereafter by config setting the language and triggering `onLanguageChanged`

**Comment by oliverfoster** [comment]
[build.zip](https://github.com/adaptlearning/adapt_framework/files/6978663/build.zip)

Example build.

**Comment by oliverfoster** [comment]
fixed in https://github.com/adaptlearning/adapt-contrib-languagePicker/pull/57

**Pull request closed without merging**
