### PR TITLE
Performance Update: jQuery1 for ie8, jQuery2 for other

### PR DESCRIPTION
**Pull request by oliverfoster**
Speed improvements and forward thinking.

This only works because the API's for jQuery 1 and 2 are identical.

http://blog.jquery.com/2014/01/24/jquery-1-11-and-2-1-released/

"For those of you not following along for a while, both the 1.x and 2.x branches of jQuery support all recent modern browsers and have the same API. The 1.x branch, this time 1.11.0, adds support for the older versions of Internet Explorer (IE6, 7, and 8). The 2.x branch, today played by 2.1.0, adds support for non-traditional web environments like node.js and browser plugins for Chrome and Firefox."

### CODE REVIEW

**Comment by oliverfoster** [comment]
fixes https://github.com/adaptlearning/adapt_framework/issues/568

**Comment by moloko** [comment]
+1
I see references to swfObject in there still, will they be removed in a separate PR?

**Comment by oliverfoster** [comment]
yea, i'll have to merge this one with https://github.com/adaptlearning/adapt_framework/pull/557 if they both go through.

**Comment by belal-almassri-spongeuk** [comment]
:+1:  Tested and working fine

**Comment by zenduo** [comment]
+1

**Comment by moloko** [comment]
+1

**Pull request merged**
