### PR TITLE
Resolves #2398, re-populates _assessmentState from 'assessments:regis…

### LINKED ISSUE #2398: Incorrect "Unknown" lesson status when completing assessment and course in different attempts
### Subject of the issue
Reported by @muthuselvan86 on Gitter.  If a course has an assessment and course content tracked as part of the completion criteria, in instances where the assessment is completed first, the session closed and then resumed, when the rest of the course content is completed the lesson status is incorrectly showing as "Unknown".

### Your environment
* Adapt Framework v3/4

### Steps to reproduce
As above.

### Expected behaviour
A "Completed" status would be written to the LMS.

### Actual behaviour
An "Unknown" status is being written because the assessment is not found.

### PR DESCRIPTION
**Pull request by brian-learningpool**
…ter'

This corrects an issue with incorrect course completion statuses being passed back
when a course was being completed over multiple sessions.

### CODE REVIEW

**Comment by oliverfoster** [comment]
Did it solve the other issue @brian-learningpool ?

**Comment by brian-learningpool** [comment]
It corrects the issue with the incorrect course status and passes the correct `assessment` state when the `tracking:complete` event is triggered.

**Comment by oliverfoster** [comment]
It reads much better also. With a clear api separation. (still, the event names are crepe).

**Comment by oliverfoster** [comment]
👁

**Comment by muthuselvan86** [comment]
Hi @brian-learningpool , it initializes the _assessmentState as soon as the app is ready(my understanding is as soon as app:dataready event triggers it calls assessment register to initialize the data). But does that bring old assessment data from session? We need to know whether the user has previously attempted the assessment(without completing lesson) and either Passed/Failed before triggering tracking:complete ?  Let me know if my understanding is not correct. Thanks.

**Pull request merged**
