### PR TITLE
Assessment upgrade

### PR DESCRIPTION
**Pull request by oliverfoster**
Added new assessment extension and results components to test course.

example: http://rawgit.com/oliverfoster/builds/assessment/index.html

### CODE REVIEW

**Comment by oliverfoster** [comment]
To be made in conjuction with PRs:

assesmentResultsTotal https://github.com/adaptlearning/adapt-contrib-assessmentResultsTotal/pull/1
assesmentResults https://github.com/adaptlearning/adapt-contrib-assessmentResults/pull/1
assesment https://github.com/adaptlearning/adapt-contrib-assessment/pull/32

**Comment by oliverfoster** [comment]
Missing the assessment article config. Will update tomorrow.

**Comment by hrajotia** [comment]
+1

**Comment by zenduo** [comment]
+1

**Comment by dancgray** [comment]
+1

**Pull request merged**
