### PR TITLE
Assessment, Trickle applied to block or article

### PR DESCRIPTION
**Pull request by belal-almassri-spongeuk**
In the assessments page, the trickle can be applied to block or article, not article only.
https://github.com/adaptlearning/adapt-contrib-trickle

### CODE REVIEW

**Comment by oliverfoster** [comment]
Use _onChildren: false for article article trickle.

**Comment by belal-almassri-spongeuk** [comment]
Hi Ollie,

I thought we can add the trickle to a particular blocks in an article as well. So the question answer for the following question should be Article and block?!

The Trickle extension makes it possible to control how the learner scrolls down the page, but what element of a page is it applied to?

**Comment by oliverfoster** [comment]
it can be applied to blocks or to the article, if on the article it can be applied to all the article's blocks or to the article itself.

**Comment by belal-almassri-spongeuk** [comment]
Cool then add +1 :-)

**Comment by oliverfoster** [comment]
+1 i got you.

**Comment by zenduo** [comment]
+1

**Comment by taylortom** [comment]
+1

**Pull request merged**
