### PR TITLE
Hotfix for slow loading in IE9

### PR DESCRIPTION
**Pull request by moloko**
see [ABU-1147](https://adaptlearning.atlassian.net/browse/ABU-1147)

### CODE REVIEW

**Comment by oliverfoster** [comment]
+1

**Comment by brian-learningpool** [comment]
+1, though do we want to leave the `console.log()` in?

**Comment by oliverfoster** [comment]
Yea, it should really be a warn. It's to indicate missing images or loading bugs. Help Matt spot this issue.

**Comment by hrajotia** [comment]
+1

**Pull request merged**
