### PR TITLE
Remove unused test suite

### PR DESCRIPTION
**Pull request by taylortom**
Partly addresses #504.

### CODE REVIEW

**Comment by oliverfoster** [comment]
very good idea

**Comment by brian-learningpool** [comment]
+1

**Comment by oliverfoster** [comment]
+1

**Comment by hrajotia** [comment]
@taylortom - should also remove these two line http://github.com/adaptlearning/adapt_framework/blob/master/.travis.yml#L5-L6

**Comment by taylortom** [comment]
Should be good to go now, had to pull in master

**Comment by moloko** [comment]
+1

**Comment by oliverfoster** [comment]
+1

**Comment by dancgray** [comment]
+1

**Pull request merged**
