### PR TITLE
issue-1167: fix bug in create-json-config

### PR DESCRIPTION
**Pull request by oliverfoster**
https://github.com/adaptlearning/adapt_framework/issues/1167

allows the framework to compile when no theme is installed

### CODE REVIEW

**Comment by lc-thomasberger** [comment]
less:compile breaks:
```
Fatal error: {
 "type": "Name",
 "filename": "src\\menu\\adapt-contrib-boxMenu\\less\\boxmenu.less",
 "index": 33,
 "line": 2,
 "callLine": null,
 "column": 8,
 "extract": [
  ".menu-title, .menu-body{",
  "\tcolor: @inverted-foreground-color;",
  "\tmargin-bottom:@menu-title-padding-bottom;"
 ],
 "message": "variable @inverted-foreground-color is undefined"
}
```
should be fixed when less variables are moved to core(theme), right?

**Comment by oliverfoster** [comment]
Yup. The fix in this PR is just for the theme.json > config.json to make it not crash.

**Comment by guywillis** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by tomgreenfield** [comment]
+1

**Pull request merged**
