### PR TITLE
Fixes #573 - Router struggles with nesting

### LINKED ISSUE #573: Bug in router navigateToParent() function when using nested pages
There seems to be an issue routing back when the page is nested inside one or more menus.  This can be replicated on a simple course structure as follows:
- Page 1
- Menu 1
    - Page 2

Using the Vanilla theme, hit the < (back) button when on Page 2.  The screen gets stuck as Loading.... due to what I think is a problem with this line:
https://github.com/adaptlearning/adapt_framework/blob/293eb9fdba452053f1bf67e5737511d5e7c05d92/src/core/js/router.js#L117

### PR DESCRIPTION
**Pull request by brian-learningpool**
- Slightly refactored router.js
- Setting model._isReady to false on AdaptView initialize()

### CODE REVIEW

**Comment by oliverfoster** [comment]
+1

**Comment by dancgray** [comment]
@brian-learningpool could you reproduce the bug in the default course or did you have to alter the course structure?

**Comment by brian-learningpool** [comment]
@dancgray, no, I didn't use the default course.  I tested with a very simple course structure as outlined in #573.  This was initially reported on the forum here:
https://community.adaptlearning.org/mod/forum/discuss.php?d=650

**Comment by dancgray** [comment]
+1, thanks @brian-learningpool

**Comment by moloko** [comment]
+1
is this going to go into develop as well?

**Comment by oliverfoster** [comment]
Yea, it needs to.

**Comment by brian-learningpool** [comment]
Thanks guys.  PR for develop is here:
https://github.com/adaptlearning/adapt_framework/pull/578

**Pull request merged**
