### PR TITLE
ABU-640: Notify and Drawer

### PR DESCRIPTION
**Pull request by oliverfoster**
Scrollbars hidden for both drawer and notify to stop background content from scrolling whilst they are open.

Added: Wait for image loading in notify, fixed notify positioning.

Fixed animations for ie9+
No animations for ie8

NOTE: Must fade the page to white in order to hide the scrollbars and prevent the user from seeing a page jump, so have minimized the effect using fadeins.

TEST ON:
iphone4 ios7
ipad mini ios8
android chrome
winxp ie8
win8 ie11 + win8 ie11:ie9 mode
win8 ff
win8 chrome
blackberry

### CODE REVIEW

**Comment by moloko** [comment]
+1

**Comment by dancgray** [comment]
+1

**Comment by oliverfoster** [comment]
brought up to date with latest merged pr's

**Comment by belal-almassri-spongeuk** [comment]
Perfect we need this feature, the only issue with it, is the page height is calculated when we open the popup only, and it is not updated when we resize the page, so if you add trickle to the article, trigger notify, and while the notify popup is open resize the page, now you can scroll!. close notify and you will notice either the some content at the end of the block is hidden or a white space between the content and the trickle button. I think we need to update the following line on page resize. 
_bodyHeight = $("body").css("height");

**Comment by oliverfoster** [comment]
1. fixed the resize whilst popup open
2. added pr for plp to wait for drawer to close https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/48

**Comment by taylortom** [comment]
[PLP PR has now been merged]

**Comment by taylortom** [comment]
Not a fan of the white flash. Is the alternative much worse?

**Comment by oliverfoster** [comment]
the alternative is to keep the scrollbars as far as i can tell. unless we can find an implementation that doesn't cause the page to jump as the scrollbars are removed.

**Comment by taylortom** [comment]
Kewl, I'll maybe create a separate low-priority issue

**Comment by taylortom** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by dancgray** [comment]
+1

**Pull request merged**
