### PR TITLE
Fixes problem with Adapt.offlineStorage not setting ready without Spoor

### LINKED ISSUE #1510: Issue with Adapt.offlineStorage introduced in v2.0.18
While testing a course with the Language Picker extension enabled the adapt content gets stuck on loading screen.

Seems to be a problem with Adapt.offlineStorage

### PR DESCRIPTION
**Pull request by ciaranlp**
This was never setting ready to true.

Converted tabs to spaces as well.

### CODE REVIEW

**Comment by ciaranlp** [comment]
Apologies I should have committed the fix separately from the formatting change, the fix is lines 22-24 with the initialize function

**Comment by oliverfoster** [comment]
I don't understand.

https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/js/adapt-offlineStorage-scorm.js#L14 < spoor sets to _isReady: false on initialize

https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/js/adapt-contrib-spoor.js#L24 < spoor sets to _isReady: true if disabled

https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/js/adapt-contrib-spoor.js#L40 < spoor sets to _isReady: true if enabled

if initialize is never called _isReady never becomes false.

**Comment by brian-learningpool** [comment]
`initialize` is called by the `new OfflineStorage()` line though.

**Comment by oliverfoster** [comment]
fair enough

**Comment by oliverfoster** [comment]
This isn't really a breaking change... is it?

**Comment by brian-learningpool** [comment]
It isn't, I'll update the wording on the ticket.

**Pull request merged**
