### PR TITLE
Resolves #2398, re-populates _assessmentState from 'assessments:regis…

### LINKED ISSUE #2398: Incorrect "Unknown" lesson status when completing assessment and course in different attempts
### Subject of the issue
Reported by @muthuselvan86 on Gitter.  If a course has an assessment and course content tracked as part of the completion criteria, in instances where the assessment is completed first, the session closed and then resumed, when the rest of the course content is completed the lesson status is incorrectly showing as "Unknown".

### Your environment
* Adapt Framework v3/4

### Steps to reproduce
As above.

### Expected behaviour
A "Completed" status would be written to the LMS.

### Actual behaviour
An "Unknown" status is being written because the assessment is not found.

### PR DESCRIPTION
**Pull request by brian-learningpool**
…ter'

This corrects an issue with incorrect course completion statuses being passed back
when a course was being completed over multiple sessions.

### CODE REVIEW

**Comment by moloko** [comment]
does this work OK if there are multiple assessments in the course? From a (cursory, admittedly) glance at the code it looks like it will call `onAssessmentRestored` once for each assessment...

**Comment by brian-learningpool** [comment]
@moloko, good catch -- you're exactly right.  I'd only tested this with a single assessment.

I think we may have to actually update the Assessment extension to trigger a new event with the overall state.

**Comment by brian-learningpool** [comment]
@oliverfoster / @moloko, `assessments:restored` actually fires once for every assessment too.  Do we actually require a new event?

**Comment by moloko** [comment]
Yeah I think that might be best TBH, everything else I can think of is pretty hacky

**Comment by moloko** [comment]
make sure to give the event a really unintuitive name though, in keeping with the style of this extension

**Pull request merged**
