### PR TITLE
New: Added `_iconClass` and `_position` properties (fixes #3512 #3397)

### LINKED ISSUE #3397: course config.json is missing drawer position config
Course [config.json](https://github.com/adaptlearning/adapt_framework/blob/d7ca095b3d90e50412f4e62bfa951a30d8a5799d/src/course/config.json#L44) hasn't been updated to include the drawer position config from the [drawer API refactor](https://github.com/adaptlearning/adapt-contrib-core/pull/219). 

Core schemas have been updated to include [_position](https://github.com/adaptlearning/adapt-contrib-core/blob/7eff5f0f4929c36b757484a8ed2d537e0ab590b2/schema/config.model.schema#L330) so I'm assuming it's just an oversight that course _config.json_ didn't get updated?

```
    "_drawer": {
        "_showEasing": "easeOutQuart",
        "_hideEasing": "easeInQuart",
        "_duration": 400,
        "_position": auto,
    },
```
Since Core has been separated  from the FW we should make a habit of updating the FW course and the wiki with any config additions/changes as part of the PR process to keep on top of the documentation housekeeping. e.g. when I was looking for drawer properties on the [wiki](https://github.com/adaptlearning/adapt_framework/wiki/Configure-your-project-with-config.json) I noticed it was last updated in 2017.

### LINKED ISSUE #3512: Add support for drawer `_iconClass`
### Subject of the enhancement
Issue [417](https://github.com/adaptlearning/adapt-contrib-core/issues/417) in `adapt-contrib-core` looks to add support for overriding the nav drawer btn icon in the course json. As a consequence, the default course will require updating to support the new JSON field. 

Potentially, as part of this fix, the other issue targeting the drawer object in config could be updated with the `_position` property https://github.com/adaptlearning/adapt_framework/issues/3397

e.g.
```
"_drawer": {
  "_showEasing": "easeOutQuart",
  "_hideEasing": "easeInQuart",
  "_duration": 400,
  "_iconClass": "icon-list"
},
```

Dependency: https://github.com/adaptlearning/adapt-contrib-core/issues/417

### Your environment
* Master AT & FW

### PR DESCRIPTION
**Pull request by guywillis**
Fixes: #3512 
Fixes #3397

### New
* Add support for overriding nav drawer btn icon from the JSON in the default course
* Add `_position` property to drawer config object

Dependency: https://github.com/adaptlearning/adapt-contrib-core/pull/498

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by joe-allen-89 — APPROVED** [review]
👍

**Review by eleanor-heath — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by joe-allen-89 — APPROVED** [review]
👍

**Comment by joe-allen-89** [comment]
Hold on dependency and bump FW!

**Review by lemmyadams — APPROVED** [review]

**Review by eleanor-heath — APPROVED** [review]

**Pull request merged**
