### PR TITLE
Hotfix/a11y focus guard less develop

### PR DESCRIPTION
**Pull request by guywillis**
Bug fix for no/touch so the focus guard functions.

### CODE REVIEW

**Comment by oliverfoster** [comment]
+1

**Comment by oliverfoster** [comment]
+1

**Comment by dancgray** [comment]
Shouldn't this one be merged into develop branch? As https://github.com/adaptlearning/adapt_framework/pull/710 is to master.

**Comment by guywillis** [comment]
It should indeed be merged into develop. Closing PR and opening a new request.

**Pull request closed without merging**
