### PR TITLE
Fixed mcq/gmcq feedback bug

### PR DESCRIPTION
**Pull request by chris-steele**

### CODE REVIEW

**Comment by chris-steele** [comment]
https://github.com/adaptlearning/adapt_framework/issues/440

Removed redundant else statement from getOptionSpecificFeedback (see also https://github.com/adaptlearning/adapt_framework/issues/440)

**Comment by oliverfoster** [comment]
+1

**Comment by zenduo** [comment]
+1

**Comment by dancgray** [comment]
+1

**Pull request merged**
